const fs = require("fs");
const { parseYmdFromJst } = require("./date-utils");
const { saveGeoCache } = require("./geo-utils");

function loadSnapshot(snapshotPath) {
  try {
    const raw = fs.readFileSync(snapshotPath, "utf8");
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

function saveSnapshot(snapshotPath, data) {
  try {
    const dir = require("path").dirname(snapshotPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(snapshotPath, JSON.stringify(data), "utf8");
  } catch (e) {
    console.warn("[snapshot] save failed:", e.message || e);
  }
}

async function batchCollect(fns, size) {
  const results = [];
  for (let i = 0; i < fns.length; i += size) {
    const batch = await Promise.all(fns.slice(i, i + size).map(f => f()));
    results.push(...batch);
  }
  return results;
}

function createGetEvents(deps) {
  const {
    CACHE_TTL_MS,
    cache,
    snapshotPath,
    geoCache,
    geoCachePath,
    collectAdditionalWardsEvents,
    collectChiyodaJidokanEvents,
    collectMeguroJidokanEvents,
    collectMinatoJidokanEvents,
    collectOtaJidokanEvents,
    collectSetagayaJidokanEvents,
    collectShibuyaJidokanEvents,
    collectShinagawaJidokanEvents,
    collectHachiojiEvents,
    collectMusashinoEvents,
    collectTachikawaEvents,
    collectAkishimaEvents,
    collectHigashiyamatoEvents,
    collectKiyoseEvents,
    collectTamaEvents,
    collectInagiEvents,
    collectHinoEvents,
    collectKokubunjiEvents,
    collectHigashikurumeEvents,
    collectMitakaEvents,
    collectKodairaEvents,
    collectHigashimurayamaEvents,
    collectKunitachiEvents,
    collectOmeEvents,
    collectHamuraEvents,
    collectKawasakiEvents,
    collectYokohamaEvents,
    collectSagamiharaEvents,
    collectEbinaEvents,
    collectKamakuraEvents,
    collectYokosukaEvents,
    collectChigasakiEvents,
    collectZamaEvents,
    collectZushiEvents,
    collectYamatoEvents,
    collectHiratsukaEvents,
    collectOdawaraEvents,
    collectHadanoEvents,
    collectAyaseEvents,
    collectAtsugiEvents,
    collectIseharaEvents,
    collectMinamiashigaraEvents,
    collectFujisawaEvents,
    collectSamukawaEvents,
    collectAikawaEvents,
    collectMiuraEvents,
    collectOisoEvents,
    collectHayamaEvents,
    collectNakaiEvents,
    collectKiyokawaEvents,
    collectNinomiyaEvents,
    collectOiEvents,
    collectYugawaraEvents,
    collectMatsudaEvents,
    collectManazuruEvents,
    collectHakoneEvents,
    collectKaiseiEvents,
    collectYamakitaEvents,
    collectMizuhoEvents,
    collectOkutamaEvents,
    collectHinodeEvents,
    collectHinoharaEvents,
    collectNagareyamaEvents,
    collectUrayasuEvents,
    collectNodaEvents,
    collectNarashinoEvents,
    collectShiroiEvents,
    collectKisarazuEvents,
    collectIsumiEvents,
    collectTohnoshoEvents,
    collectOtakiEvents,
    collectFunabashiEvents,
    collectNaritaEvents,
    collectChibaCityEvents,
    collectKashiwaEvents,
    collectYachiyoEvents,
    collectAsahiEvents,
    collectKamogawaEvents,
    collectYokoshibahikariEvents,
    collectIchikawaEvents,
    collectKatsuuraEvents,
    collectKimitsuEvents,
    collectKyonanEvents,
    collectYotsukaidoEvents,
    collectMatsudoEvents,
    collectAbikoEvents,
    collectKamagayaEvents,
    collectTomisatoEvents,
    collectShirakoEvents,
    collectKujukuriEvents,
    collectYachimataEvents,
    collectSodegauraEvents,
    collectIchinomiyaEvents,
    collectChoshiEvents,
    collectSakuraEvents,
    collectFuttsuEvents,
    collectInzaiEvents,
    collectKatoriEvents,
    collectToganeEvents,
    collectIchiharaEvents,
    collectSosaEvents,
    collectSammuEvents,
    collectSakaeChibaEvents,
    collectMobaraEvents,
    collectTateyamaEvents,
    collectMinamibosoEvents,
    collectOamishirasatoEvents,
    collectShisuiEvents,
    collectKozakiEvents,
    collectTakoEvents,
    collectShibayamaEvents,
    collectMutsuzawaEvents,
    collectChoseiEvents,
    collectNagaraEvents,
    collectOnjukuEvents,
    collectChonanEvents,
    collectKawaguchiEvents,
    collectKasukabeEvents,
    collectFujiminoEvents,
    collectMisatoEvents,
    collectKawagoeEvents,
    collectWakoEvents,
    collectWarabiEvents,
    collectAgeoEvents,
    collectNiizaEvents,
    collectAsakaEvents,
    collectTodaEvents,
    collectShikiEvents,
    collectFujimiEvents,
    collectSayamaEvents,
    collectYashioEvents,
    collectSaitamaEvents,
    collectKoshigayaEvents,
  } = deps;

  return async function getEvents(maxDays, refresh) {
  const days = Math.min(Math.max(Number(maxDays) || 30, 1), 90);
  const cacheKey = `jidokan:${days}`;

  // Normal user access: return cached data only, never scrape
  if (!refresh) {
    if (cache.data && cache.key === cacheKey) {
      return {
        ...cache.data,
        from_cache: true,
        snapshot_saved_at: new Date(cache.savedAt).toISOString(),
      };
    }
    if (snapshotPath) {
      const snapshot = loadSnapshot(snapshotPath);
      if (snapshot) {
        cache.key = cacheKey;
        cache.data = snapshot;
        cache.savedAt = Date.now();
        console.log("[snapshot] loaded from disk:", snapshotPath);
        return {
          ...snapshot,
          from_cache: true,
          snapshot_saved_at: new Date(cache.savedAt).toISOString(),
        };
      }
    }
    return {
      date_jst: "",
      count: 0,
      source: "tokyo_jidokan",
      items: [],
      debug_counts: { raw: {} },
      from_cache: true,
      snapshot_saved_at: null,
    };
  }

  // refresh=1 (cron only): actually scrape

  const [setagaya, ota, shinagawa, meguro, shibuya, minato, chiyoda, additional, hachioji, musashino, tachikawa, akishima, higashiyamato, kiyose, tama, inagi, hino, kokubunji, higashikurume, mitaka, kodaira, higashimurayama, kunitachi, ome, hamura, kawasaki, yokohama, sagamihara, ebina, kamakura, yokosuka, chigasaki, zama, zushi, yamato, hiratsuka, odawara, hadano, ayase, atsugi, isehara, minamiashigara, fujisawa, samukawa, aikawa, miura, oiso, hayama, nakai, kiyokawa, ninomiya, oi, yugawara, matsuda, manazuru, hakone, kaisei, yamakita, mizuho, okutama, hinode, hinohara, nagareyama, urayasu, noda, narashino, shiroi, kisarazu, isumi, tohnosho, otaki, funabashi, narita, chibaCity, kashiwa, yachiyo, asahi, kamogawa, yokoshibahikari, ichikawa, katsuura, kimitsu, kyonan, yotsukaido, matsudo, abiko, kamagaya, tomisato, shirako, kujukuri, yachimata, sodegaura, ichinomiya, choshi, sakura, futtsu, inzai, katori, togane, ichihara, sosa, sammu, sakaeChiba, mobara, tateyama, minamiboso, oamishirasato, shisui, kozaki, tako, shibayama, mutsuzawa, chosei, nagara, onjuku, chonan, kawaguchi, kasukabe, fujimino, misato, kawagoe, wako, warabi, ageo, niiza, asaka, toda, shiki, fujimi, sayama, yashio, saitamaCity, koshigaya] = await batchCollect([
    () => collectSetagayaJidokanEvents(days),
    () => collectOtaJidokanEvents(days),
    () => collectShinagawaJidokanEvents(days),
    () => collectMeguroJidokanEvents(days),
    () => collectShibuyaJidokanEvents(days),
    () => collectMinatoJidokanEvents(days),
    () => collectChiyodaJidokanEvents(days),
    () => collectAdditionalWardsEvents(days),
    () => collectHachiojiEvents(days),
    () => collectMusashinoEvents(days),
    () => collectTachikawaEvents(days),
    () => collectAkishimaEvents(days),
    () => collectHigashiyamatoEvents(days),
    () => collectKiyoseEvents(days),
    () => collectTamaEvents(days),
    () => collectInagiEvents(days),
    () => collectHinoEvents(days),
    () => collectKokubunjiEvents(days),
    () => collectHigashikurumeEvents(days),
    () => collectMitakaEvents(days),
    () => collectKodairaEvents(days),
    () => collectHigashimurayamaEvents(days),
    () => collectKunitachiEvents(days),
    () => collectOmeEvents(days),
    () => collectHamuraEvents(days),
    () => collectKawasakiEvents(days),
    () => collectYokohamaEvents(days),
    () => collectSagamiharaEvents(days),
    () => collectEbinaEvents(days),
    () => collectKamakuraEvents(days),
    () => collectYokosukaEvents(days),
    () => collectChigasakiEvents(days),
    () => collectZamaEvents(days),
    () => collectZushiEvents(days),
    () => collectYamatoEvents(days),
    () => collectHiratsukaEvents(days),
    () => collectOdawaraEvents(days),
    () => collectHadanoEvents(days),
    () => collectAyaseEvents(days),
    () => collectAtsugiEvents(days),
    () => collectIseharaEvents(days),
    () => collectMinamiashigaraEvents(days),
    () => collectFujisawaEvents(days),
    () => collectSamukawaEvents(days),
    () => collectAikawaEvents(days),
    () => collectMiuraEvents(days),
    () => collectOisoEvents(days),
    () => collectHayamaEvents(days),
    () => collectNakaiEvents(days),
    () => collectKiyokawaEvents(days),
    () => collectNinomiyaEvents(days),
    () => collectOiEvents(days),
    () => collectYugawaraEvents(days),
    () => collectMatsudaEvents(days),
    () => collectManazuruEvents(days),
    () => collectHakoneEvents(days),
    () => collectKaiseiEvents(days),
    () => collectYamakitaEvents(days),
    () => collectMizuhoEvents(days),
    () => collectOkutamaEvents(days),
    () => collectHinodeEvents(days),
    () => collectHinoharaEvents(days),
    () => collectNagareyamaEvents(days),
    () => collectUrayasuEvents(days),
    () => collectNodaEvents(days),
    () => collectNarashinoEvents(days),
    () => collectShiroiEvents(days),
    () => collectKisarazuEvents(days),
    () => collectIsumiEvents(days),
    () => collectTohnoshoEvents(days),
    () => collectOtakiEvents(days),
    () => collectFunabashiEvents(days),
    () => collectNaritaEvents(days),
    () => collectChibaCityEvents(days),
    () => collectKashiwaEvents(days),
    () => collectYachiyoEvents(days),
    () => collectAsahiEvents(days),
    () => collectKamogawaEvents(days),
    () => collectYokoshibahikariEvents(days),
    () => collectIchikawaEvents(days),
    () => collectKatsuuraEvents(days),
    () => collectKimitsuEvents(days),
    () => collectKyonanEvents(days),
    () => collectYotsukaidoEvents(days),
    () => collectMatsudoEvents(days),
    () => collectAbikoEvents(days),
    () => collectKamagayaEvents(days),
    () => collectTomisatoEvents(days),
    () => collectShirakoEvents(days),
    () => collectKujukuriEvents(days),
    () => collectYachimataEvents(days),
    () => collectSodegauraEvents(days),
    () => collectIchinomiyaEvents(days),
    () => collectChoshiEvents(days),
    () => collectSakuraEvents(days),
    () => collectFuttsuEvents(days),
    () => collectInzaiEvents(days),
    () => collectKatoriEvents(days),
    () => collectToganeEvents(days),
    () => collectIchiharaEvents(days),
    () => collectSosaEvents(days),
    () => collectSammuEvents(days),
    () => collectSakaeChibaEvents(days),
    () => collectMobaraEvents(days),
    () => collectTateyamaEvents(days),
    () => collectMinamibosoEvents(days),
    () => collectOamishirasatoEvents(days),
    () => collectShisuiEvents(days),
    () => collectKozakiEvents(days),
    () => collectTakoEvents(days),
    () => collectShibayamaEvents(days),
    () => collectMutsuzawaEvents(days),
    () => collectChoseiEvents(days),
    () => collectNagaraEvents(days),
    () => collectOnjukuEvents(days),
    () => collectChonanEvents(days),
    () => collectKawaguchiEvents(days),
    () => collectKasukabeEvents(days),
    () => collectFujiminoEvents(days),
    () => collectMisatoEvents(days),
    () => collectKawagoeEvents(days),
    () => collectWakoEvents(days),
    () => collectWarabiEvents(days),
    () => collectAgeoEvents(days),
    () => collectNiizaEvents(days),
    () => collectAsakaEvents(days),
    () => collectTodaEvents(days),
    () => collectShikiEvents(days),
    () => collectFujimiEvents(days),
    () => collectSayamaEvents(days),
    () => collectYashioEvents(days),
    () => collectSaitamaEvents(days),
    () => collectKoshigayaEvents(days),
  ], 5);
  const {
    chuo,
    bunkyo,
    taito,
    sumida,
    koto,
    nakano,
    suginami,
    toshima,
    kita,
    arakawa,
    itabashi,
    nerima,
    adachi,
    katsushika,
    edogawa,
    shinjuku,
    chofu,
    fuchu,
    koganei,
    nishitokyo,
    machida,
    fussa,
    musashimurayama,
    akiruno,
    komae,
  } = additional;
  const rawItems = [
    ...setagaya,
    ...ota,
    ...shinagawa,
    ...meguro,
    ...shibuya,
    ...minato,
    ...chiyoda,
    ...chuo,
    ...bunkyo,
    ...taito,
    ...sumida,
    ...koto,
    ...nakano,
    ...suginami,
    ...toshima,
    ...kita,
    ...arakawa,
    ...itabashi,
    ...nerima,
    ...adachi,
    ...katsushika,
    ...edogawa,
    ...shinjuku,
    ...chofu,
    ...hachioji,
    ...musashino,
    ...tachikawa,
    ...akishima,
    ...higashiyamato,
    ...kiyose,
    ...tama,
    ...inagi,
    ...hino,
    ...kokubunji,
    ...higashikurume,
    ...fuchu,
    ...koganei,
    ...nishitokyo,
    ...machida,
    ...fussa,
    ...musashimurayama,
    ...akiruno,
    ...komae,
    ...mitaka,
    ...kodaira,
    ...higashimurayama,
    ...kunitachi,
    ...ome,
    ...hamura,
    ...kawasaki,
    ...yokohama,
    ...sagamihara,
    ...ebina,
    ...kamakura,
    ...yokosuka,
    ...chigasaki,
    ...zama,
    ...zushi,
    ...yamato,
    ...hiratsuka,
    ...odawara,
    ...hadano,
    ...ayase,
    ...atsugi,
    ...isehara,
    ...minamiashigara,
    ...fujisawa,
    ...samukawa,
    ...aikawa,
    ...miura,
    ...oiso,
    ...hayama,
    ...nakai,
    ...kiyokawa,
    ...ninomiya,
    ...oi,
    ...yugawara,
    ...matsuda,
    ...manazuru,
    ...hakone,
    ...kaisei,
    ...yamakita,
    ...mizuho,
    ...okutama,
    ...hinode,
    ...hinohara,
    ...nagareyama,
    ...urayasu,
    ...noda,
    ...narashino,
    ...shiroi,
    ...kisarazu,
    ...isumi,
    ...tohnosho,
    ...otaki,
    ...funabashi,
    ...narita,
    ...chibaCity,
    ...kashiwa,
    ...yachiyo,
    ...asahi,
    ...kamogawa,
    ...yokoshibahikari,
    ...ichikawa,
    ...katsuura,
    ...kimitsu,
    ...kyonan,
    ...yotsukaido,
    ...matsudo,
    ...abiko,
    ...kamagaya,
    ...tomisato,
    ...shirako,
    ...kujukuri,
    ...yachimata,
    ...sodegaura,
    ...ichinomiya,
    ...choshi,
    ...sakura,
    ...futtsu,
    ...inzai,
    ...katori,
    ...togane,
    ...ichihara,
    ...sosa,
    ...sammu,
    ...sakaeChiba,
    ...mobara,
    ...tateyama,
    ...minamiboso,
    ...oamishirasato,
    ...shisui,
    ...kozaki,
    ...tako,
    ...shibayama,
    ...mutsuzawa,
    ...chosei,
    ...nagara,
    ...onjuku,
    ...chonan,
    ...kawaguchi,
    ...kasukabe,
    ...fujimino,
    ...misato,
    ...kawagoe,
    ...wako,
    ...warabi,
    ...ageo,
    ...niiza,
    ...asaka,
    ...toda,
    ...shiki,
    ...fujimi,
    ...sayama,
    ...yashio,
    ...saitamaCity,
    ...koshigaya,
  ];
  const items = rawItems
    .map((ev) => {
      const { point, query_hit, recently_updated, ...rest } = ev;
      if (typeof rest.time_unknown === "boolean") return rest;
      let inferredUnknown = false;
      if (!rest.ends_at && rest.starts_at) {
        const d = new Date(rest.starts_at);
        if (!Number.isNaN(d.getTime())) {
          const hm = new Intl.DateTimeFormat("ja-JP", {
            timeZone: "Asia/Tokyo",
            hour: "2-digit",
            minute: "2-digit",
            hour12: false,
          }).format(d);
          inferredUnknown = hm === "00:00";
        }
      }
      return { ...rest, time_unknown: inferredUnknown };
    })
    .sort((a, b) => a.starts_at.localeCompare(b.starts_at));
  const now = parseYmdFromJst(new Date());
  const end = new Date();
  end.setUTCDate(end.getUTCDate() + days);
  const endJst = parseYmdFromJst(end);

  const payload = {
    date_jst: `${now.key}..${endJst.key}`,
    count: items.length,
    source: "tokyo_jidokan",
    debug_counts: {
      raw: {
        ward_setagaya: setagaya.length,
        ward_ota: ota.length,
        ward_shinagawa: shinagawa.length,
        ward_meguro: meguro.length,
        ward_shibuya: shibuya.length,
        ward_minato: minato.length,
        ward_chiyoda: chiyoda.length,
        ward_chuo: chuo.length,
        ward_bunkyo: bunkyo.length,
        ward_taito: taito.length,
        ward_sumida: sumida.length,
        ward_koto: koto.length,
        ward_nakano: nakano.length,
        ward_suginami: suginami.length,
        ward_toshima: toshima.length,
        ward_kita: kita.length,
        ward_arakawa: arakawa.length,
        ward_itabashi: itabashi.length,
        ward_nerima: nerima.length,
        ward_adachi: adachi.length,
        ward_katsushika: katsushika.length,
        ward_edogawa: edogawa.length,
        ward_shinjuku: shinjuku.length,
        city_chofu: chofu.length,
        city_hachioji: hachioji.length,
        city_musashino: musashino.length,
        city_tachikawa: tachikawa.length,
        city_akishima: akishima.length,
        city_higashiyamato: higashiyamato.length,
        city_kiyose: kiyose.length,
        city_tama: tama.length,
        city_inagi: inagi.length,
        city_hino: hino.length,
        city_kokubunji: kokubunji.length,
        city_higashikurume: higashikurume.length,
        city_fuchu: fuchu.length,
        city_koganei: koganei.length,
        city_nishitokyo: nishitokyo.length,
        city_machida: machida.length,
        city_fussa: fussa.length,
        city_musashimurayama: musashimurayama.length,
        city_akiruno: akiruno.length,
        city_komae: komae.length,
        city_mitaka: mitaka.length,
        city_kodaira: kodaira.length,
        city_higashimurayama: higashimurayama.length,
        city_kunitachi: kunitachi.length,
        city_ome: ome.length,
        city_hamura: hamura.length,
        city_kawasaki: kawasaki.length,
        city_yokohama: yokohama.length,
        city_sagamihara: sagamihara.length,
        city_ebina: ebina.length,
        city_kamakura: kamakura.length,
        city_yokosuka: yokosuka.length,
        city_chigasaki: chigasaki.length,
        city_zama: zama.length,
        city_zushi: zushi.length,
        city_yamato: yamato.length,
        city_hiratsuka: hiratsuka.length,
        city_odawara: odawara.length,
        city_hadano: hadano.length,
        city_ayase: ayase.length,
        city_atsugi: atsugi.length,
        city_isehara: isehara.length,
        city_minamiashigara: minamiashigara.length,
        city_fujisawa: fujisawa.length,
        town_samukawa: samukawa.length,
        town_aikawa: aikawa.length,
        city_miura: miura.length,
        town_oiso: oiso.length,
        town_hayama: hayama.length,
        town_nakai: nakai.length,
        village_kiyokawa: kiyokawa.length,
        town_ninomiya: ninomiya.length,
        town_oi: oi.length,
        town_yugawara: yugawara.length,
        town_matsuda: matsuda.length,
        town_manazuru: manazuru.length,
        town_hakone: hakone.length,
        town_kaisei: kaisei.length,
        town_yamakita: yamakita.length,
        town_mizuho: mizuho.length,
        town_okutama: okutama.length,
        town_hinode: hinode.length,
        village_hinohara: hinohara.length,
        city_nagareyama: nagareyama.length,
        city_urayasu: urayasu.length,
        city_noda: noda.length,
        city_narashino: narashino.length,
        city_shiroi: shiroi.length,
        city_kisarazu: kisarazu.length,
        city_isumi: isumi.length,
        town_tohnosho: tohnosho.length,
        town_otaki: otaki.length,
        city_funabashi: funabashi.length,
        city_narita: narita.length,
        city_chiba: chibaCity.length,
        city_kashiwa: kashiwa.length,
        city_yachiyo: yachiyo.length,
        city_asahi: asahi.length,
        city_kamogawa: kamogawa.length,
        town_yokoshibahikari: yokoshibahikari.length,
        city_ichikawa: ichikawa.length,
        city_katsuura: katsuura.length,
        city_kimitsu: kimitsu.length,
        town_kyonan: kyonan.length,
        city_yotsukaido: yotsukaido.length,
        city_matsudo: matsudo.length,
        city_abiko: abiko.length,
        city_kamagaya: kamagaya.length,
        city_tomisato: tomisato.length,
        town_shirako: shirako.length,
        town_kujukuri: kujukuri.length,
        city_yachimata: yachimata.length,
        city_sodegaura: sodegaura.length,
        town_ichinomiya: ichinomiya.length,
        city_choshi: choshi.length,
        city_sakura: sakura.length,
        city_futtsu: futtsu.length,
        city_inzai: inzai.length,
        city_katori: katori.length,
        city_togane: togane.length,
        city_ichihara: ichihara.length,
        city_sosa: sosa.length,
        city_sammu: sammu.length,
        town_sakae_chiba: sakaeChiba.length,
        city_mobara: mobara.length,
        city_tateyama: tateyama.length,
        city_minamiboso: minamiboso.length,
        city_oamishirasato: oamishirasato.length,
        town_shisui: shisui.length,
        town_kozaki: kozaki.length,
        town_tako: tako.length,
        town_shibayama: shibayama.length,
        town_mutsuzawa: mutsuzawa.length,
        vill_chosei: chosei.length,
        town_nagara: nagara.length,
        town_onjuku: onjuku.length,
        town_chonan: chonan.length,
        city_kawaguchi: kawaguchi.length,
        city_kasukabe: kasukabe.length,
        city_fujimino: fujimino.length,
        city_misato: misato.length,
        city_kawagoe: kawagoe.length,
        city_wako: wako.length,
        city_warabi: warabi.length,
        city_ageo: ageo.length,
        city_niiza: niiza.length,
        city_asaka: asaka.length,
        city_toda: toda.length,
        city_shiki: shiki.length,
        city_fujimi: fujimi.length,
        city_sayama: sayama.length,
        city_yashio: yashio.length,
        city_saitama: saitamaCity.length,
        city_koshigaya: koshigaya.length,
      },
    },
    items,
    refresh_in_progress: false,
  };

  cache.key = cacheKey;
  cache.data = payload;
  cache.savedAt = Date.now();

  if (snapshotPath) saveSnapshot(snapshotPath, payload);
  if (geoCachePath && geoCache) saveGeoCache(geoCachePath, geoCache);

  return {
    ...payload,
    from_cache: false,
    snapshot_saved_at: new Date(cache.savedAt).toISOString(),
  };
};
}

module.exports = {
  createGetEvents,
};
