const fs = require("fs");
const { parseYmdFromJst } = require("./date-utils");
const { saveGeoCache } = require("./geo-utils");

function loadSnapshot(snapshotPath) {
  try {
    const raw = fs.readFileSync(snapshotPath, "utf8");
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

function saveSnapshot(snapshotPath, data) {
  try {
    const dir = require("path").dirname(snapshotPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(snapshotPath, JSON.stringify(data), "utf8");
  } catch (e) {
    console.warn("[snapshot] save failed:", e.message || e);
  }
}

async function batchCollect(fns, size) {
  const results = [];
  for (let i = 0; i < fns.length; i += size) {
    const batch = await Promise.all(fns.slice(i, i + size).map(async (f, j) => {
      try {
        return await f();
      } catch (e) {
        console.error(`[batchCollect] collector #${i + j} failed:`, e.message, e.stack?.split("\n")[1]);
        return [];
      }
    }));
    results.push(...batch);
  }
  return results;
}

function createGetEvents(deps) {
  const {
    CACHE_TTL_MS,
    cache,
    snapshotPath,
    geoCache,
    geoCachePath,
    collectAdditionalWardsEvents,
    collectChiyodaJidokanEvents,
    collectMeguroJidokanEvents,
    collectMinatoJidokanEvents,
    collectOtaJidokanEvents,
    collectSetagayaJidokanEvents,
    collectShibuyaJidokanEvents,
    collectShinagawaJidokanEvents,
    collectHachiojiEvents,
    collectMusashinoEvents,
    collectTachikawaEvents,
    collectAkishimaEvents,
    collectHigashiyamatoEvents,
    collectKiyoseEvents,
    collectTamaEvents,
    collectInagiEvents,
    collectHinoEvents,
    collectKokubunjiEvents,
    collectHigashikurumeEvents,
    collectMitakaEvents,
    collectKodairaEvents,
    collectHigashimurayamaEvents,
    collectKunitachiEvents,
    collectOmeEvents,
    collectHamuraEvents,
    collectKawasakiEvents,
    collectYokohamaEvents,
    collectSagamiharaEvents,
    collectEbinaEvents,
    collectKamakuraEvents,
    collectKamakuraKmspotEvents,
    collectYokosukaEvents,
    collectChigasakiEvents,
    collectZamaEvents,
    collectZushiEvents,
    collectYamatoEvents,
    collectHiratsukaEvents,
    collectHiratsukaLibraryEvents,
    collectOdawaraEvents,
    collectHadanoEvents,
    collectAyaseEvents,
    collectAtsugiEvents,
    collectAtsugiKosodateEvents,
    collectIseharaEvents,
    collectMinamiashigaraEvents,
    collectFujisawaEvents,
    collectSamukawaEvents,
    collectAikawaEvents,
    collectMiuraEvents,
    collectOisoEvents,
    collectHayamaEvents,
    collectNakaiEvents,
    collectKiyokawaEvents,
    collectNinomiyaEvents,
    collectOiEvents,
    collectYugawaraEvents,
    collectMatsudaEvents,
    collectManazuruEvents,
    collectHakoneEvents,
    collectKaiseiEvents,
    collectYamakitaEvents,
    collectMachidaKosodateEvents,
    collectMizuhoEvents,
    collectOkutamaEvents,
    collectHinodeEvents,
    collectHinoharaEvents,
    collectNagareyamaEvents,
    collectUrayasuEvents,
    collectNodaEvents,
    collectNarashinoEvents,
    collectShiroiEvents,
    collectKisarazuEvents,
    collectIsumiEvents,
    collectTohnoshoEvents,
    collectOtakiEvents,
    collectFunabashiEvents,
    collectNaritaEvents,
    collectChibaCityEvents,
    collectChibaCityWardEvents,
    collectKashiwaEvents,
    collectYachiyoEvents,
    collectAsahiEvents,
    collectKamogawaEvents,
    collectYokoshibahikariEvents,
    collectIchikawaEvents,
    collectIchikawaIkujiEvents,
    collectKatsuuraEvents,
    collectKimitsuEvents,
    collectKyonanEvents,
    collectYotsukaidoEvents,
    collectMatsudoEvents,
    collectAbikoEvents,
    collectKamagayaEvents,
    collectTomisatoEvents,
    collectShirakoEvents,
    collectKujukuriEvents,
    collectYachimataEvents,
    collectSodegauraEvents,
    collectIchinomiyaEvents,
    collectChoshiEvents,
    collectSakuraEvents,
    collectFuttsuEvents,
    collectInzaiEvents,
    collectKatoriEvents,
    collectToganeEvents,
    collectIchiharaEvents,
    collectSosaEvents,
    collectSammuEvents,
    collectSakaeChibaEvents,
    collectMobaraEvents,
    collectTateyamaEvents,
    collectMinamibosoEvents,
    collectOamishirasatoEvents,
    collectShisuiEvents,
    collectKozakiEvents,
    collectTakoEvents,
    collectShibayamaEvents,
    collectMutsuzawaEvents,
    collectChoseiEvents,
    collectNagaraEvents,
    collectOnjukuEvents,
    collectChonanEvents,
    collectKimitsuKosodateEvents,
    collectMatsudoKosodateEvents,
    collectMatsudoLibraryEvents,
    collectIchiharaKodomomiraiEvents,
    collectIchiharaSalonEvents,
    collectNaritaKosodateEvents,
    collectAbikoKosodateEvents,
    collectKamagayaKosodateEvents,
    collectSakuraLibraryEvents,
    collectInzaiLibraryEvents,
    collectKawaguchiEvents,
    collectKasukabeEvents,
    collectFujiminoEvents,
    collectMisatoEvents,
    collectKawagoeEvents,
    collectWakoEvents,
    collectWarabiEvents,
    collectAgeoEvents,
    collectNiizaEvents,
    collectAsakaEvents,
    collectTodaEvents,
    collectShikiEvents,
    collectFujimiEvents,
    collectSayamaEvents,
    collectYashioEvents,
    collectSaitamaEvents,
    collectSaitamaJidoukanEvents,
    collectSaitamaHokenEvents,
    collectKoshigayaEvents,
    collectKoshigayaKosodateEvents,
    collectTokorozawaEvents,
    collectKukiEvents,
    collectKumagayaEvents,
    collectKounosuEvents,
    collectSakadoEvents,
    collectHannoEvents,
    collectHigashimatsuyamaEvents,
    collectGyodaEvents,
    collectHonjoEvents,
    collectHidakaEvents,
    collectShiraokaEvents,
    collectSatteEvents,
    collectYoriiEvents,
    collectSugitoEvents,
    collectSokaEvents,
    collectTsurugashimaEvents,
    collectHasudaEvents,
    collectIrumaEvents,
    collectKazoEvents,
    collectFukayaEvents,
    collectOkegawaEvents,
    collectOgoseEvents,
    collectOgawaEvents,
    collectYoshimiEvents,
    collectKamikawaEvents,
    collectKamisatoEvents,
    collectYoshikawaEvents,
    collectOganoEvents,
    collectHigashichichibEvents,
    collectKawajimaEvents,
    collectKitamotoEvents,
    collectInaEvents,
    collectYokozeEvents,
    collectNagatoroEvents,
    collectMiyoshiEvents,
    collectHatoyamaEvents,
    collectMiyashiroEvents,
    collectChichibuEvents,
    collectNamegawaEvents,
    collectRanzanEvents,
    collectMatsubushiEvents,
    collectMinanoEvents,
    collectMoroyamaEvents,
    collectHanyuEvents,
    collectMisatoSaitamaEvents,
    // Tochigi
    collectSanoEvents,
    collectNikkoEvents,
    collectMokaEvents,
    collectNasushiobaraEvents,
    collectTochigiCityEvents,
    collectYaitaEvents,
    collectUtsunomiyaEvents,
    collectAshikagaEvents,
    collectKanumaEvents,
    collectOyamaEvents,
    collectOhtawaraEvents,
    collectTochigiSakuraEvents,
    collectNasukarasuyamaEvents,
    collectShimotsukeEvents,
    collectKaminokawaEvents,
    collectMashikoEvents,
    collectMotegiEvents,
    collectIchikaiEvents,
    collectHagaEvents,
    collectMibuEvents,
    collectNogiEvents,
    collectShioyaEvents,
    collectTakanezawaEvents,
    collectNasuEvents,
    collectTochigiNakagawaEvents,
    // Gunma
    collectMaebashiEvents,
    collectIsesakiEvents,
    collectFujiokaGunmaEvents,
    collectTakasakiEvents,
    collectOtaGunmaEvents,
    collectAnnakaEvents,
    collectNakanojoEvents,
    collectKiryuEvents,
    collectNumataEvents,
    collectTatebayashiEvents,
    collectShibukawaEvents,
    collectTomiokaEvents,
    collectMidoriEvents,
    collectShintoEvents,
    collectYoshiokaEvents,
    collectUenoGunmaEvents,
    collectKannaEvents,
    collectShimonitaEvents,
    collectNanmokuEvents,
    collectKanraEvents,
    collectNaganoharaEvents,
    collectTsumagoiEvents,
    collectKusatsuEvents,
    collectTakayamaGunmaEvents,
    collectHigashiagatsumaEvents,
    collectKatashinaEvents,
    collectKawabaEvents,
    collectShowaGunmaEvents,
    collectMinakamiEvents,
    collectTamamuraEvents,
    collectItakuraEvents,
    collectMeiwaGunmaEvents,
    collectChiyodaGunmaEvents,
    collectOizumiEvents,
    collectOraEvents,
    // Tochigi schedule supplement
    collectNasuScheduleEvents,
    collectTakanezawaScheduleEvents,
    collectNikkoScheduleEvents,
    collectNikkoSupportCenterEvents,
    collectNasushiobaraScheduleEvents,
    collectOyamaScheduleEvents,
    collectOhtawaraScheduleEvents,
    collectAshikagaScheduleEvents,
    collectShimotsukeScheduleEvents,
    collectTochigiSakuraScheduleEvents,
    collectOhtawaraPdfScheduleEvents,
    collectKanumaPdfScheduleEvents,
    collectNasukarasuyamaPdfScheduleEvents,
    // PDF schedule collectors
    collectOtaGunmaPdfScheduleEvents,
    collectShibukawaPdfScheduleEvents,
    collectTomiokaPdfScheduleEvents,
    collectAnnakaPdfScheduleEvents,
    collectMinakamiPdfScheduleEvents,
    collectMeiwaPdfScheduleEvents,
    collectShintoPdfScheduleEvents,
    // Gunma schedule supplements
    collectMaebashiScheduleEvents,
    collectIsesakiScheduleEvents,
    collectKiryuScheduleEvents,
    collectTatebayashiScheduleEvents,
    collectNumataScheduleEvents,
    collectKawabaScheduleEvents,
    collectShimonitaScheduleEvents,
    collectChiyodaGunmaScheduleEvents,
    collectFujiokaGunmaScheduleEvents,
    collectTamamuraScheduleEvents,
    collectKanraScheduleEvents,
    collectAnnakaScheduleEvents,
    collectHigashiagatsumaScheduleEvents,
    collectItakuraCalendarEvents,
    collectMidoriScheduleEvents,
    collectOizumiScheduleEvents,
    collectOtaKodomokanEvents,
    collectKiryuShienCenterEvents,
    collectNakanojoRecurringEvents,
    collectShimonitaCrossRowEvents,
    collectTakasakiNandemoEvents,
  } = deps;

  return async function getEvents(maxDays, refresh) {
  const days = Math.min(Math.max(Number(maxDays) || 30, 1), 90);
  const cacheKey = `jidokan:${days}`;

  // Normal user access: return cached data only, never scrape
  if (!refresh) {
    if (cache.data && cache.key === cacheKey) {
      return {
        ...cache.data,
        from_cache: true,
        snapshot_saved_at: new Date(cache.savedAt).toISOString(),
      };
    }
    if (snapshotPath) {
      const snapshot = loadSnapshot(snapshotPath);
      if (snapshot) {
        cache.key = cacheKey;
        cache.data = snapshot;
        cache.savedAt = Date.now();
        console.log("[snapshot] loaded from disk:", snapshotPath);
        return {
          ...snapshot,
          from_cache: true,
          snapshot_saved_at: new Date(cache.savedAt).toISOString(),
        };
      }
    }
    return {
      date_jst: "",
      count: 0,
      source: "tokyo_jidokan",
      items: [],
      debug_counts: { raw: {} },
      from_cache: true,
      snapshot_saved_at: null,
    };
  }

  // refresh=1 (cron only): actually scrape

  const allCollectorResults = await batchCollect([
    () => collectSetagayaJidokanEvents(days),
    () => collectOtaJidokanEvents(days),
    () => collectShinagawaJidokanEvents(days),
    () => collectMeguroJidokanEvents(days),
    () => collectShibuyaJidokanEvents(days),
    () => collectMinatoJidokanEvents(days),
    () => collectChiyodaJidokanEvents(days),
    () => collectAdditionalWardsEvents(days),
    () => collectHachiojiEvents(days),
    () => collectMusashinoEvents(days),
    () => collectTachikawaEvents(days),
    () => collectAkishimaEvents(days),
    () => collectHigashiyamatoEvents(days),
    () => collectKiyoseEvents(days),
    () => collectTamaEvents(days),
    () => collectInagiEvents(days),
    () => collectHinoEvents(days),
    () => collectKokubunjiEvents(days),
    () => collectHigashikurumeEvents(days),
    () => collectMitakaEvents(days),
    () => collectKodairaEvents(days),
    () => collectHigashimurayamaEvents(days),
    () => collectKunitachiEvents(days),
    () => collectOmeEvents(days),
    () => collectHamuraEvents(days),
    () => collectKawasakiEvents(days),
    () => collectYokohamaEvents(days),
    () => collectSagamiharaEvents(days),
    () => collectEbinaEvents(days),
    () => collectKamakuraEvents(days),
    () => collectKamakuraKmspotEvents(days),
    () => collectYokosukaEvents(days),
    () => collectChigasakiEvents(days),
    () => collectZamaEvents(days),
    () => collectZushiEvents(days),
    () => collectYamatoEvents(days),
    () => collectHiratsukaEvents(days),
    () => collectHiratsukaLibraryEvents(days),
    () => collectOdawaraEvents(days),
    () => collectHadanoEvents(days),
    () => collectAyaseEvents(days),
    () => collectAtsugiEvents(days),
    () => collectAtsugiKosodateEvents(days),
    () => collectIseharaEvents(days),
    () => collectMinamiashigaraEvents(days),
    () => collectFujisawaEvents(days),
    () => collectSamukawaEvents(days),
    () => collectAikawaEvents(days),
    () => collectMiuraEvents(days),
    () => collectOisoEvents(days),
    () => collectHayamaEvents(days),
    () => collectNakaiEvents(days),
    () => collectKiyokawaEvents(days),
    () => collectNinomiyaEvents(days),
    () => collectOiEvents(days),
    () => collectYugawaraEvents(days),
    () => collectMatsudaEvents(days),
    () => collectManazuruEvents(days),
    () => collectHakoneEvents(days),
    () => collectKaiseiEvents(days),
    () => collectYamakitaEvents(days),
    () => collectMachidaKosodateEvents(days),
    () => collectMizuhoEvents(days),
    () => collectOkutamaEvents(days),
    () => collectHinodeEvents(days),
    () => collectHinoharaEvents(days),
    () => collectNagareyamaEvents(days),
    () => collectUrayasuEvents(days),
    () => collectNodaEvents(days),
    () => collectNarashinoEvents(days),
    () => collectShiroiEvents(days),
    () => collectKisarazuEvents(days),
    () => collectIsumiEvents(days),
    () => collectTohnoshoEvents(days),
    () => collectOtakiEvents(days),
    () => collectFunabashiEvents(days),
    () => collectNaritaEvents(days),
    () => collectChibaCityEvents(days),
    () => collectChibaCityWardEvents(days),
    () => collectKashiwaEvents(days),
    () => collectYachiyoEvents(days),
    () => collectAsahiEvents(days),
    () => collectKamogawaEvents(days),
    () => collectYokoshibahikariEvents(days),
    () => collectIchikawaEvents(days),
    () => collectIchikawaIkujiEvents(days),
    () => collectKatsuuraEvents(days),
    () => collectKimitsuEvents(days),
    () => collectKyonanEvents(days),
    () => collectYotsukaidoEvents(days),
    () => collectMatsudoEvents(days),
    () => collectAbikoEvents(days),
    () => collectKamagayaEvents(days),
    () => collectTomisatoEvents(days),
    () => collectShirakoEvents(days),
    () => collectKujukuriEvents(days),
    () => collectYachimataEvents(days),
    () => collectSodegauraEvents(days),
    () => collectIchinomiyaEvents(days),
    () => collectChoshiEvents(days),
    () => collectSakuraEvents(days),
    () => collectFuttsuEvents(days),
    () => collectInzaiEvents(days),
    () => collectKatoriEvents(days),
    () => collectToganeEvents(days),
    () => collectIchiharaEvents(days),
    () => collectSosaEvents(days),
    () => collectSammuEvents(days),
    () => collectSakaeChibaEvents(days),
    () => collectMobaraEvents(days),
    () => collectTateyamaEvents(days),
    () => collectMinamibosoEvents(days),
    () => collectOamishirasatoEvents(days),
    () => collectShisuiEvents(days),
    () => collectKozakiEvents(days),
    () => collectTakoEvents(days),
    () => collectShibayamaEvents(days),
    () => collectMutsuzawaEvents(days),
    () => collectChoseiEvents(days),
    () => collectNagaraEvents(days),
    () => collectOnjukuEvents(days),
    () => collectChonanEvents(days),
    () => collectKimitsuKosodateEvents(days),
    () => collectMatsudoKosodateEvents(days),
    () => collectMatsudoLibraryEvents(days),
    () => collectIchiharaKodomomiraiEvents(days),
    () => collectIchiharaSalonEvents(days),
    () => collectNaritaKosodateEvents(days),
    () => collectAbikoKosodateEvents(days),
    () => collectKamagayaKosodateEvents(days),
    () => collectSakuraLibraryEvents(days),
    () => collectInzaiLibraryEvents(days),
    () => collectKawaguchiEvents(days),
    () => collectKasukabeEvents(days),
    () => collectFujiminoEvents(days),
    () => collectMisatoEvents(days),
    () => collectKawagoeEvents(days),
    () => collectWakoEvents(days),
    () => collectWarabiEvents(days),
    () => collectAgeoEvents(days),
    () => collectNiizaEvents(days),
    () => collectAsakaEvents(days),
    () => collectTodaEvents(days),
    () => collectShikiEvents(days),
    () => collectFujimiEvents(days),
    () => collectSayamaEvents(days),
    () => collectYashioEvents(days),
    () => collectSaitamaEvents(days),
    () => collectSaitamaJidoukanEvents(days),
    () => collectSaitamaHokenEvents(days),
    () => collectKoshigayaEvents(days),
    () => collectKoshigayaKosodateEvents(days),
    () => collectTokorozawaEvents(days),
    () => collectKukiEvents(days),
    () => collectKumagayaEvents(days),
    () => collectKounosuEvents(days),
    () => collectSakadoEvents(days),
    () => collectHannoEvents(days),
    () => collectHigashimatsuyamaEvents(days),
    () => collectGyodaEvents(days),
    () => collectHonjoEvents(days),
    () => collectHidakaEvents(days),
    () => collectShiraokaEvents(days),
    () => collectSatteEvents(days),
    () => collectYoriiEvents(days),
    () => collectSugitoEvents(days),
    () => collectSokaEvents(days),
    () => collectTsurugashimaEvents(days),
    () => collectHasudaEvents(days),
    () => collectIrumaEvents(days),
    () => collectKazoEvents(days),
    () => collectFukayaEvents(days),
    () => collectOkegawaEvents(days),
    () => collectOgoseEvents(days),
    () => collectOgawaEvents(days),
    () => collectYoshimiEvents(days),
    () => collectKamikawaEvents(days),
    () => collectKamisatoEvents(days),
    () => collectYoshikawaEvents(days),
    () => collectOganoEvents(days),
    () => collectHigashichichibEvents(days),
    () => collectKawajimaEvents(days),
    () => collectKitamotoEvents(days),
    () => collectInaEvents(days),
    () => collectYokozeEvents(days),
    () => collectNagatoroEvents(days),
    () => collectMiyoshiEvents(days),
    () => collectHatoyamaEvents(days),
    () => collectMiyashiroEvents(days),
    () => collectChichibuEvents(days),
    () => collectNamegawaEvents(days),
    () => collectRanzanEvents(days),
    () => collectMatsubushiEvents(days),
    () => collectMinanoEvents(days),
    () => collectMoroyamaEvents(days),
    () => collectHanyuEvents(days),
    () => collectMisatoSaitamaEvents(days),
    // Tochigi
    () => collectSanoEvents(days),
    () => collectNikkoEvents(days),
    () => collectMokaEvents(days),
    () => collectNasushiobaraEvents(days),
    () => collectTochigiCityEvents(days),
    () => collectYaitaEvents(days),
    () => collectUtsunomiyaEvents(days),
    () => collectAshikagaEvents(days),
    () => collectKanumaEvents(days),
    () => collectOyamaEvents(days),
    () => collectOhtawaraEvents(days),
    () => collectTochigiSakuraEvents(days),
    () => collectNasukarasuyamaEvents(days),
    () => collectShimotsukeEvents(days),
    () => collectKaminokawaEvents(days),
    () => collectMashikoEvents(days),
    () => collectMotegiEvents(days),
    () => collectIchikaiEvents(days),
    () => collectHagaEvents(days),
    () => collectMibuEvents(days),
    () => collectNogiEvents(days),
    () => collectShioyaEvents(days),
    () => collectTakanezawaEvents(days),
    () => collectNasuEvents(days),
    () => collectTochigiNakagawaEvents(days),
    // Gunma
    () => collectMaebashiEvents(days),
    () => collectIsesakiEvents(days),
    () => collectFujiokaGunmaEvents(days),
    () => collectTakasakiEvents(days),
    () => collectOtaGunmaEvents(days),
    () => collectAnnakaEvents(days),
    () => collectNakanojoEvents(days),
    () => collectKiryuEvents(days),
    () => collectNumataEvents(days),
    () => collectTatebayashiEvents(days),
    () => collectShibukawaEvents(days),
    () => collectTomiokaEvents(days),
    () => collectMidoriEvents(days),
    () => collectShintoEvents(days),
    () => collectYoshiokaEvents(days),
    () => collectUenoGunmaEvents(days),
    () => collectKannaEvents(days),
    () => collectShimonitaEvents(days),
    () => collectNanmokuEvents(days),
    () => collectKanraEvents(days),
    () => collectNaganoharaEvents(days),
    () => collectTsumagoiEvents(days),
    () => collectKusatsuEvents(days),
    () => collectTakayamaGunmaEvents(days),
    () => collectHigashiagatsumaEvents(days),
    () => collectKatashinaEvents(days),
    () => collectKawabaEvents(days),
    () => collectShowaGunmaEvents(days),
    () => collectMinakamiEvents(days),
    () => collectTamamuraEvents(days),
    () => collectItakuraEvents(days),
    () => collectMeiwaGunmaEvents(days),
    () => collectChiyodaGunmaEvents(days),
    () => collectOizumiEvents(days),
    () => collectOraEvents(days),
    // Tochigi schedule supplement
    () => collectNasuScheduleEvents(days),
    () => collectTakanezawaScheduleEvents(days),
    () => collectNikkoScheduleEvents(days),
    () => collectNikkoSupportCenterEvents(days),
    () => collectNasushiobaraScheduleEvents(days),
    () => collectOyamaScheduleEvents(days),
    () => collectOhtawaraScheduleEvents(days),
    () => collectAshikagaScheduleEvents(days),
    () => collectShimotsukeScheduleEvents(days),
    () => collectTochigiSakuraScheduleEvents(days),
    () => collectOhtawaraPdfScheduleEvents(days),
    () => collectKanumaPdfScheduleEvents(days),
    () => collectNasukarasuyamaPdfScheduleEvents(days),
    // PDF schedule collectors
    () => collectOtaGunmaPdfScheduleEvents(days),
    () => collectShibukawaPdfScheduleEvents(days),
    () => collectTomiokaPdfScheduleEvents(days),
    () => collectAnnakaPdfScheduleEvents(days),
    () => collectMinakamiPdfScheduleEvents(days),
    () => collectMeiwaPdfScheduleEvents(days),
    () => collectShintoPdfScheduleEvents(days),
    // Gunma schedule supplements
    () => collectMaebashiScheduleEvents(days),
    () => collectIsesakiScheduleEvents(days),
    () => collectKiryuScheduleEvents(days),
    () => collectTatebayashiScheduleEvents(days),
    () => collectNumataScheduleEvents(days),
    () => collectKawabaScheduleEvents(days),
    () => collectShimonitaScheduleEvents(days),
    () => collectChiyodaGunmaScheduleEvents(days),
    () => collectFujiokaGunmaScheduleEvents(days),
    () => collectTamamuraScheduleEvents(days),
    () => collectKanraScheduleEvents(days),
    () => collectAnnakaScheduleEvents(days),
    () => collectHigashiagatsumaScheduleEvents(days),
    () => collectItakuraCalendarEvents(days),
    () => collectMidoriScheduleEvents(days),
    () => collectOizumiScheduleEvents(days),
    () => collectOtaKodomokanEvents(days),
    () => collectKiryuShienCenterEvents(days),
    () => collectNakanojoRecurringEvents(days),
    () => collectShimonitaCrossRowEvents(days),
    () => collectTakasakiNandemoEvents(days),
  ], 5);
  // Flatten all collector results into a single array.
  // Most collectors return an array; additional-wards returns an object of arrays.
  const rawItems = [];
  for (const result of allCollectorResults) {
    if (Array.isArray(result)) {
      rawItems.push(...result);
    } else if (result && typeof result === "object") {
      for (const arr of Object.values(result)) {
        if (Array.isArray(arr)) rawItems.push(...arr);
      }
    }
  }
  const items = rawItems
    .map((ev) => {
      const { point, query_hit, recently_updated, ...rest } = ev;
      if (typeof rest.time_unknown === "boolean") return rest;
      let inferredUnknown = false;
      if (!rest.ends_at && rest.starts_at) {
        const d = new Date(rest.starts_at);
        if (!Number.isNaN(d.getTime())) {
          const hm = new Intl.DateTimeFormat("ja-JP", {
            timeZone: "Asia/Tokyo",
            hour: "2-digit",
            minute: "2-digit",
            hour12: false,
          }).format(d);
          inferredUnknown = hm === "00:00";
        }
      }
      return { ...rest, time_unknown: inferredUnknown };
    })
    .sort((a, b) => a.starts_at.localeCompare(b.starts_at));
  const now = parseYmdFromJst(new Date());
  const end = new Date();
  end.setUTCDate(end.getUTCDate() + days);
  const endJst = parseYmdFromJst(end);

  const payload = {
    date_jst: `${now.key}..${endJst.key}`,
    count: items.length,
    source: "tokyo_jidokan",
    debug_counts: {
      raw: (() => {
        const counts = {};
        for (const ev of rawItems) {
          const key = ev.source || "unknown";
          counts[key] = (counts[key] || 0) + 1;
        }
        return counts;
      })(),
    },
    items,
    refresh_in_progress: false,
  };

  cache.key = cacheKey;
  cache.data = payload;
  cache.savedAt = Date.now();

  if (snapshotPath) saveSnapshot(snapshotPath, payload);
  if (geoCachePath && geoCache) saveGeoCache(geoCachePath, geoCache);

  return {
    ...payload,
    from_cache: false,
    snapshot_saved_at: new Date(cache.savedAt).toISOString(),
  };
};
}

module.exports = {
  createGetEvents,
};
