const fs = require("fs");
const { parseYmdFromJst } = require("./date-utils");
const { saveGeoCache } = require("./geo-utils");

function loadSnapshot(snapshotPath) {
  try {
    const raw = fs.readFileSync(snapshotPath, "utf8");
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

function saveSnapshot(snapshotPath, data) {
  try {
    const dir = require("path").dirname(snapshotPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(snapshotPath, JSON.stringify(data), "utf8");
  } catch (e) {
    console.warn("[snapshot] save failed:", e.message || e);
  }
}

async function batchCollect(fns, size) {
  const results = [];
  for (let i = 0; i < fns.length; i += size) {
    const batch = await Promise.all(fns.slice(i, i + size).map(async (f, j) => {
      try {
        return await f();
      } catch (e) {
        console.error(`[batchCollect] collector #${i + j} failed:`, e.message, e.stack?.split("\n")[1]);
        return [];
      }
    }));
    results.push(...batch);
  }
  return results;
}

function createGetEvents(deps) {
  const {
    CACHE_TTL_MS,
    cache,
    snapshotPath,
    geoCache,
    geoCachePath,
    collectAdditionalWardsEvents,
    collectChiyodaJidokanEvents,
    collectMeguroJidokanEvents,
    collectMinatoJidokanEvents,
    collectOtaJidokanEvents,
    collectSetagayaJidokanEvents,
    collectShibuyaJidokanEvents,
    collectShinagawaJidokanEvents,
    collectHachiojiEvents,
    collectMusashinoEvents,
    collectTachikawaEvents,
    collectAkishimaEvents,
    collectHigashiyamatoEvents,
    collectKiyoseEvents,
    collectTamaEvents,
    collectInagiEvents,
    collectHinoEvents,
    collectKokubunjiEvents,
    collectHigashikurumeEvents,
    collectMitakaEvents,
    collectKodairaEvents,
    collectHigashimurayamaEvents,
    collectKunitachiEvents,
    collectOmeEvents,
    collectHamuraEvents,
    collectKawasakiEvents,
    collectYokohamaEvents,
    collectSagamiharaEvents,
    collectEbinaEvents,
    collectKamakuraEvents,
    collectKamakuraKmspotEvents,
    collectYokosukaEvents,
    collectChigasakiEvents,
    collectZamaEvents,
    collectZushiEvents,
    collectYamatoEvents,
    collectHiratsukaEvents,
    collectHiratsukaLibraryEvents,
    collectOdawaraEvents,
    collectHadanoEvents,
    collectAyaseEvents,
    collectAtsugiEvents,
    collectAtsugiKosodateEvents,
    collectIseharaEvents,
    collectMinamiashigaraEvents,
    collectFujisawaEvents,
    collectSamukawaEvents,
    collectAikawaEvents,
    collectMiuraEvents,
    collectOisoEvents,
    collectHayamaEvents,
    collectNakaiEvents,
    collectKiyokawaEvents,
    collectNinomiyaEvents,
    collectOiEvents,
    collectYugawaraEvents,
    collectMatsudaEvents,
    collectManazuruEvents,
    collectHakoneEvents,
    collectKaiseiEvents,
    collectYamakitaEvents,
    collectMachidaKosodateEvents,
    collectMizuhoEvents,
    collectOkutamaEvents,
    collectHinodeEvents,
    collectHinoharaEvents,
    collectNagareyamaEvents,
    collectUrayasuEvents,
    collectNodaEvents,
    collectNarashinoEvents,
    collectShiroiEvents,
    collectKisarazuEvents,
    collectIsumiEvents,
    collectTohnoshoEvents,
    collectOtakiEvents,
    collectFunabashiEvents,
    collectNaritaEvents,
    collectChibaCityEvents,
    collectChibaCityWardEvents,
    collectKashiwaEvents,
    collectYachiyoEvents,
    collectAsahiEvents,
    collectKamogawaEvents,
    collectYokoshibahikariEvents,
    collectIchikawaEvents,
    collectIchikawaIkujiEvents,
    collectKatsuuraEvents,
    collectKimitsuEvents,
    collectKyonanEvents,
    collectYotsukaidoEvents,
    collectMatsudoEvents,
    collectAbikoEvents,
    collectKamagayaEvents,
    collectTomisatoEvents,
    collectShirakoEvents,
    collectKujukuriEvents,
    collectYachimataEvents,
    collectSodegauraEvents,
    collectIchinomiyaEvents,
    collectChoshiEvents,
    collectSakuraEvents,
    collectFuttsuEvents,
    collectInzaiEvents,
    collectKatoriEvents,
    collectToganeEvents,
    collectIchiharaEvents,
    collectSosaEvents,
    collectSammuEvents,
    collectSakaeChibaEvents,
    collectMobaraEvents,
    collectTateyamaEvents,
    collectMinamibosoEvents,
    collectOamishirasatoEvents,
    collectShisuiEvents,
    collectKozakiEvents,
    collectTakoEvents,
    collectShibayamaEvents,
    collectMutsuzawaEvents,
    collectChoseiEvents,
    collectNagaraEvents,
    collectOnjukuEvents,
    collectChonanEvents,
    collectKimitsuKosodateEvents,
    collectMatsudoKosodateEvents,
    collectMatsudoLibraryEvents,
    collectIchiharaKodomomiraiEvents,
    collectIchiharaSalonEvents,
    collectNaritaKosodateEvents,
    collectAbikoKosodateEvents,
    collectKamagayaKosodateEvents,
    collectSakuraLibraryEvents,
    collectInzaiLibraryEvents,
    collectKawaguchiEvents,
    collectKasukabeEvents,
    collectFujiminoEvents,
    collectMisatoEvents,
    collectKawagoeEvents,
    collectWakoEvents,
    collectWarabiEvents,
    collectAgeoEvents,
    collectNiizaEvents,
    collectAsakaEvents,
    collectTodaEvents,
    collectShikiEvents,
    collectFujimiEvents,
    collectSayamaEvents,
    collectYashioEvents,
    collectSaitamaEvents,
    collectSaitamaJidoukanEvents,
    collectSaitamaHokenEvents,
    collectKoshigayaEvents,
    collectKoshigayaKosodateEvents,
    collectTokorozawaEvents,
    collectKukiEvents,
    collectKumagayaEvents,
    collectKounosuEvents,
    collectSakadoEvents,
    collectHannoEvents,
    collectHigashimatsuyamaEvents,
    collectGyodaEvents,
    collectHonjoEvents,
    collectHidakaEvents,
    collectShiraokaEvents,
    collectSatteEvents,
    collectYoriiEvents,
    collectSugitoEvents,
    collectSokaEvents,
    collectTsurugashimaEvents,
    collectHasudaEvents,
    collectIrumaEvents,
    collectKazoEvents,
    collectFukayaEvents,
    collectOkegawaEvents,
    collectOgoseEvents,
    collectOgawaEvents,
    collectYoshimiEvents,
    collectKamikawaEvents,
    collectKamisatoEvents,
    collectYoshikawaEvents,
    collectOganoEvents,
    collectHigashichichibEvents,
    collectKawajimaEvents,
    collectKitamotoEvents,
    collectInaEvents,
    collectYokozeEvents,
    collectNagatoroEvents,
    collectMiyoshiEvents,
    collectHatoyamaEvents,
    collectMiyashiroEvents,
    collectChichibuEvents,
    collectNamegawaEvents,
    collectRanzanEvents,
    collectMatsubushiEvents,
    collectMinanoEvents,
    collectMoroyamaEvents,
    collectHanyuEvents,
    collectMisatoSaitamaEvents,
    // Tochigi
    collectSanoEvents,
    collectNikkoEvents,
    collectMokaEvents,
    collectNasushiobaraEvents,
    collectTochigiCityEvents,
    collectYaitaEvents,
    collectUtsunomiyaEvents,
    collectAshikagaEvents,
    collectKanumaEvents,
    collectOyamaEvents,
    collectOhtawaraEvents,
    collectTochigiSakuraEvents,
    collectNasukarasuyamaEvents,
    collectShimotsukeEvents,
    collectKaminokawaEvents,
    collectMashikoEvents,
    collectMotegiEvents,
    collectIchikaiEvents,
    collectHagaEvents,
    collectMibuEvents,
    collectNogiEvents,
    collectShioyaEvents,
    collectTakanezawaEvents,
    collectNasuEvents,
    collectTochigiNakagawaEvents,
    // Gunma
    collectMaebashiEvents,
    collectIsesakiEvents,
    collectFujiokaGunmaEvents,
    collectTakasakiEvents,
    collectOtaGunmaEvents,
    collectAnnakaEvents,
    collectNakanojoEvents,
    collectKiryuEvents,
    collectNumataEvents,
    collectTatebayashiEvents,
    collectShibukawaEvents,
    collectTomiokaEvents,
    collectMidoriEvents,
    collectShintoEvents,
    collectYoshiokaEvents,
    collectUenoGunmaEvents,
    collectKannaEvents,
    collectShimonitaEvents,
    collectNanmokuEvents,
    collectKanraEvents,
    collectNaganoharaEvents,
    collectTsumagoiEvents,
    collectKusatsuEvents,
    collectTakayamaGunmaEvents,
    collectHigashiagatsumaEvents,
    collectKatashinaEvents,
    collectKawabaEvents,
    collectShowaGunmaEvents,
    collectMinakamiEvents,
    collectTamamuraEvents,
    collectItakuraEvents,
    collectMeiwaGunmaEvents,
    collectChiyodaGunmaEvents,
    collectOizumiEvents,
    collectOraEvents,
    // Tochigi schedule supplement
    collectNasuScheduleEvents,
    collectTakanezawaScheduleEvents,
    collectNikkoScheduleEvents,
    collectNikkoSupportCenterEvents,
    collectNasushiobaraScheduleEvents,
    collectOyamaScheduleEvents,
    collectOhtawaraScheduleEvents,
    collectAshikagaScheduleEvents,
    collectShimotsukeScheduleEvents,
    collectTochigiSakuraScheduleEvents,
    collectOhtawaraPdfScheduleEvents,
    collectKanumaPdfScheduleEvents,
    collectNasukarasuyamaPdfScheduleEvents,
    // PDF schedule collectors
    collectOtaGunmaPdfScheduleEvents,
    collectShibukawaPdfScheduleEvents,
    collectTomiokaPdfScheduleEvents,
    collectAnnakaPdfScheduleEvents,
    collectMinakamiPdfScheduleEvents,
    collectMeiwaPdfScheduleEvents,
    collectShintoPdfScheduleEvents,
    // Gunma schedule supplements
    collectMaebashiScheduleEvents,
    collectIsesakiScheduleEvents,
    collectKiryuScheduleEvents,
    collectTatebayashiScheduleEvents,
    collectNumataScheduleEvents,
    collectKawabaScheduleEvents,
    collectShimonitaScheduleEvents,
    collectChiyodaGunmaScheduleEvents,
    collectFujiokaGunmaScheduleEvents,
    collectTamamuraScheduleEvents,
    collectKanraScheduleEvents,
    collectAnnakaScheduleEvents,
    collectHigashiagatsumaScheduleEvents,
    collectItakuraCalendarEvents,
    collectMidoriScheduleEvents,
    collectOizumiScheduleEvents,
    collectOtaKodomokanEvents,
    collectKiryuShienCenterEvents,
    collectNakanojoRecurringEvents,
    collectShimonitaCrossRowEvents,
    collectTakasakiNandemoEvents,
    // Katsushika schedule supplement
    collectKatsushikaScheduleEvents,
    // Ibaraki
    collectHitachiIbEvents,
    collectHitachinakaEvents,
    collectMoriyaEvents,
    collectKamisuEvents,
    collectTokaiIbEvents,
    collectKogaIbEvents,
    collectTsukubaEvents,
    collectRyugasakiEvents,
    collectTorideEvents,
    collectMitoEvents,
    collectKashimaIbEvents,
    collectKasamaEvents,
    collectChikuseiEvents,
    collectTsuchiuraEvents,
    collectIshiokaEvents,
    collectJosoEvents,
    collectNakaIbEvents,
    collectBandoEvents,
    collectHitachiotaEvents,
    collectYukiEvents,
    collectTsukubamiraiEvents,
    collectInashikiEvents,
    collectSakuragawaEvents,
    collectHitachiomiyaEvents,
    collectShimotsumaEvents,
    collectHokotaEvents,
    collectNamegataEvents,
    collectItakoEvents,
    collectKasumigauraEvents,
    collectTakahagiEvents,
    collectShiroIbEvents,
    collectSakaiIbEvents,
    collectDaigoEvents,
    collectYachiyoIbEvents,
    collectGokaEvents,
    collectOaraiEvents,
    collectKawachiIbEvents,
    collectIbarakimachiEvents,
    collectKitaibarakiEvents,
    collectUshikuEvents,
    collectAmiEvents,
    collectToneIbEvents,
    // 東北6県
    collectHachinoheEvents, collectTsugaruEvents, collectHiranaiEvents, collectNakadomariEvents, collectYomogitaEvents, collectItayanagiEvents,
    collectKitakamiEvents, collectKujiEvents, collectOshuEvents, collectNishiwagaEvents, collectIchinoheEvents, collectOtsuchiEvents,
    collectMiyagiSendaiEvents, collectIshinomakiEvents, collectHigashimatsushimaEvents, collectZaoEvents, collectShichikashukuEvents, collectShichigahamaEvents, collectTaiwaEvents, collectShikamaEvents, collectNatoriEvents, collectShiogamaEvents,
    collectAkitaKosodateEvents, collectYokoteEvents, collectYurihonjyoEvents, collectOgaEvents, collectKosakaEvents, collectHachirogataEvents,
    collectYonezawaEvents, collectSakataEvents, collectShinjoEvents, collectNagaiEvents, collectNakayamaYmEvents, collectKahokuEvents, collectAsahiYmEvents, collectKaneyamaYmEvents, collectMamurogawaEvents, collectOkuraEvents, collectShiratakaEvents,
    collectFukushimaCityEvents, collectSomaEvents, collectMinamisomaEvents, collectOtamaEvents, collectShimogoEvents, collectAizumisatoEvents, collectFurudonoEvents,
    // 北海道
    collectHokkaidoIwamizawaEvents, collectHokkaidoShibetsuEvents, collectHokkaidoChitoseEvents, collectHokkaidoMoriEvents, collectHokkaidoOzoraEvents, collectHokkaidoTsubetsuEvents, collectHokkaidoTaikiEvents, collectHokkaidoNisekoEvents, collectHokkaidoShiraoiEvents, collectHokkaidoHigashikaguraEvents, collectHokkaidoOtoineppuEvents, collectHokkaidoYubetsuEvents, collectHokkaidoNakasatsunaiEvents, collectHokkaidoSarabetsuEvents, collectHokkaidoHonbetsuEvents, collectHokkaidoHirooEvents, collectHokkaidoShikaoiEvents, collectHokkaidoAkkeshiEvents, collectHokkaidoBetsukaiEvents, collectHokkaidoNakashibetsuEvents, collectHokkaidoShibetsuChoEvents, collectHokkaidoShintokuEvents, collectHokkaidoKutchanEvents, collectHokkaidoHaboroEvents,
    // 中部
    collectNiigataSanjoEvents, collectNiigataKashiwazakiEvents, collectNiigataTsubameEvents, collectNiigataAganoEvents, collectNiigataSeiroEvents, collectNiigataYuzawaEvents, collectNiigataKamoEvents, collectNiigataMinamiuonumaEvents, collectNiigataTagamiEvents, collectToyamaHimiEvents, collectToyamaNamerikawaEvents, collectToyamaKurobeEvents, collectToyamaNyuzenEvents, collectToyamaAsahiTyEvents, collectIshikawaKanazawaEvents, collectIshikawaKomatsuEvents, collectIshikawaKagaEvents, collectIshikawaNakanotoEvents, collectFukuiFukuikuEvents, collectFukuiSabaeEvents, collectYamanashiChuoEvents, collectYamanashiMinamialpsEvents, collectYamanashiHokutoEvents, collectNaganoSuzakaEvents, collectNaganoKomaganeEvents, collectNaganoChikumaEvents, collectNaganoIijimachoEvents, collectNaganoMatsukawaEvents, collectNaganoIkedaEvents, collectGifuOgakiEvents, collectGifuSekiEvents, collectGifuEnaEvents, collectGifuMotosuEvents, collectGifuKaizuEvents, collectGifuAnpachiEvents, collectGifuIbigawaEvents, collectGifuOnoGfEvents, collectShizuokaFujiedaEvents, collectShizuokaSusonoEvents, collectShizuokaKosaiEvents, collectShizuokaIzuEvents, collectShizuokaOmaezakiEvents, collectShizuokaNagaizumiEvents, collectShizuokaKannamiEvents, collectShizuokaHamamatsuEvents, collectShizuokaCityEvents, collectAichiToyokawaEvents, collectAichiHekinanEvents, collectAichiShinshiroEvents, collectAichiChiryuEvents, collectAichiInazawaEvents, collectAichiIwakuraEvents, collectAichiNisshinEvents, collectAichiAisaiEvents, collectAichiMiyoshiEvents, collectAichiNagakuteEvents, collectAichiTogoEvents, collectAichiAguiEvents, collectAichiHigashiuraEvents, collectAichiOwariasahiEvents, collectAichiKomakiEvents, collectAichiNagoyaEvents, collectAichiToyotaEvents, collectAichiKasugaiEvents, collectAichiIchinomiyaEvents, collectGifuGifuEvents,
    // 近畿
    collectShigaOtsuEvents, collectShigaMoriyamaEvents, collectMieTsuEvents, collectMieTobaEvents, collectMieOwaseEvents, collectMieIgaEvents, collectMieKisosakiEvents, collectMieTakiEvents, collectMieMeiwaEvents, collectShigaHikoneEvents, collectShigaNagahamaEvents, collectShigaOmihachimanEvents, collectShigaKokaEvents, collectShigaMaibaraEvents, collectShigaAishoEvents, collectShigaHinoEvents, collectShigaToyosatoEvents, collectKyotoMamafreEvents, collectKyotoWakutobiEvents, collectKyotoMaizuruEvents, collectKyotoAyabeEvents, collectKyotoJoyoEvents, collectKyotoNagaokakyoEvents, collectKyotoYawataEvents, collectKyotoSeikaEvents, collectKyotoKumiyamaEvents, collectKyotoMinamiyamashiroEvents, collectKyotoKameokaEvents, collectKyotoUjiEvents, collectKyotoMukoEvents, collectOsakaIkedaEvents, collectOsakaIzumiotsuEvents, collectOsakaKaizukaEvents, collectOsakaMoriguchiEvents, collectOsakaIbarakiEvents, collectOsakaHirakataEvents, collectOsakaNeyagawaEvents, collectOsakaIzumiEvents, collectOsakaHabikinoEvents, collectOsakaFujiideraEvents, collectOsakaHigashiosakaEvents, collectOsakaSennanEvents, collectOsakaHannanEvents, collectOsakaKumatoriEvents, collectOsakaTadaokaEvents, collectOsakaTaishiEvents, collectOsakaTakatsukiEvents, collectOsakaKishiwadaEvents, collectOsakaKawachinaganoEvents, collectOsakaTondabayashiEvents, collectOsakaSakaiEvents, collectOsakaSuitaEvents, collectHyogoAshiyaEvents, collectHyogoHimejiEvents, collectHyogoItamiEvents, collectHyogoKakogawaEvents, collectHyogoTatsunoEvents, collectHyogoOnoEvents, collectHyogoShisoEvents, collectHyogoKatoEvents, collectHyogoInagawaEvents, collectHyogoInamiEvents, collectHyogoFukusakiEvents, collectHyogoKamikawaEvents, collectNaraTenriEvents, collectNaraKashiharaEvents, collectNaraGojoEvents, collectNaraGoseEvents, collectNaraIkomaEvents, collectNaraIkarugaEvents, collectNaraAndoEvents, collectNaraKawanishiNrEvents, collectNaraTawaramotoEvents, collectNaraOjiEvents, collectNaraKoryoEvents, collectNaraAsukaEvents, collectNaraTotsukawaEvents, collectNaraShimoichiEvents, collectWakayamaHashimotoEvents, collectWakayamaInamiWkEvents,
    // 中国・四国
    collectTottoriKosodateEvents, collectTottoriNichinanEvents, collectTottoriSakaiminatoEvents, collectShimaneMasudaEvents, collectShimaneAmaEvents, collectOkayamaOkayamaEvents, collectOkayamaAkaiwaEvents, collectOkayamaMimasakaEvents, collectOkayamaHayashimaEvents, collectHiroshimaIkuchanEvents, collectHiroshimaFuchuEvents, collectHiroshimaOtakeEvents, collectHiroshimaHigashihiroshimaEvents, collectHiroshimaFukuyamaEvents, collectHiroshimaKureEvents, collectHiroshimaOnomichiEvents, collectHiroshimaMiharaEvents, collectHiroshimaHatsukaichiEvents, collectYamaguchiHikariEvents, collectYamaguchiShimonosekiEvents, collectYamaguchiYamaguchiEvents, collectYamaguchiShunanEvents, collectTokushimaTokushimaEvents, collectTokushimaNakaEvents, collectTokushimaHigashimiyoshiEvents, collectKagawaTakamatsuEvents, collectKagawaSanukiEvents, collectKagawaMitoyoEvents, collectKagawaTonoshoEvents, collectEhimeSeiyoEvents, collectEhimeTobeEvents, collectKochiMurotoEvents, collectKochiKokohareEvents,
    // 九州・沖縄
    collectFukuokaKitakyushuEvents, collectFukuokaFukutsuEvents, collectFukuokaShinguFkEvents, collectFukuokaHirokawaEvents, collectFukuokaKawaraEvents, collectFukuokaChikushinoEvents, collectFukuokaNakagawaEvents, collectNagasakiTsushimaEvents, collectNagasakiIkiEvents, collectNagasakiSaikaiEvents, collectNagasakiTogitsuEvents, collectNagasakiHigashisonogiEvents, collectSagaKaratsuEvents, collectSagaTosuEvents, collectKumamotoTakamoriEvents, collectKumamotoKikuchiEvents, collectOitaHitaEvents, collectOitaTaketaEvents, collectOitaKitsukiEvents, collectOitaKusuEvents, collectMiyazakiMiyazakiEvents, collectMiyazakiNichinanEvents, collectMiyazakiKijoEvents, collectMiyazakiKadogawaEvents, collectMiyazakiMiyakojoEvents, collectKagoshimaSatsumasendaiEvents, collectKagoshimaMinamikyushuEvents, collectKagoshimaSatsumaEvents, collectKagoshimaKimotsukiEvents, collectHokkaidoSapporoEvents, collectOitaOitaEvents, collectOkinawaNahaEvents, collectOkinawaYomitanEvents, collectOkinawaKitanakagusukuEvents, collectOkinawaIeEvents, collectShizuokaAtamiEvents, collectShizuokaItoEvents, collectAichiKiyosuEvents, collectOkayamaKibichuoEvents,
  } = deps;

  return async function getEvents(maxDays, refresh) {
  const days = Math.min(Math.max(Number(maxDays) || 30, 1), 90);
  const cacheKey = `jidokan:${days}`;

  // Normal user access: return cached data only, never scrape
  if (!refresh) {
    if (cache.data && cache.key === cacheKey) {
      return {
        ...cache.data,
        from_cache: true,
        snapshot_saved_at: new Date(cache.savedAt).toISOString(),
      };
    }
    if (snapshotPath) {
      const snapshot = loadSnapshot(snapshotPath);
      if (snapshot) {
        cache.key = cacheKey;
        cache.data = snapshot;
        cache.savedAt = Date.now();
        console.log("[snapshot] loaded from disk:", snapshotPath);
        return {
          ...snapshot,
          from_cache: true,
          snapshot_saved_at: new Date(cache.savedAt).toISOString(),
        };
      }
    }
    return {
      date_jst: "",
      count: 0,
      source: "tokyo_jidokan",
      items: [],
      debug_counts: { raw: {} },
      from_cache: true,
      snapshot_saved_at: null,
    };
  }

  // refresh=1 (cron only): actually scrape

  const allCollectorResults = await batchCollect([
    () => collectSetagayaJidokanEvents(days),
    () => collectOtaJidokanEvents(days),
    () => collectShinagawaJidokanEvents(days),
    () => collectMeguroJidokanEvents(days),
    () => collectShibuyaJidokanEvents(days),
    () => collectMinatoJidokanEvents(days),
    () => collectChiyodaJidokanEvents(days),
    () => collectAdditionalWardsEvents(days),
    () => collectHachiojiEvents(days),
    () => collectMusashinoEvents(days),
    () => collectTachikawaEvents(days),
    () => collectAkishimaEvents(days),
    () => collectHigashiyamatoEvents(days),
    () => collectKiyoseEvents(days),
    () => collectTamaEvents(days),
    () => collectInagiEvents(days),
    () => collectHinoEvents(days),
    () => collectKokubunjiEvents(days),
    () => collectHigashikurumeEvents(days),
    () => collectMitakaEvents(days),
    () => collectKodairaEvents(days),
    () => collectHigashimurayamaEvents(days),
    () => collectKunitachiEvents(days),
    () => collectOmeEvents(days),
    () => collectHamuraEvents(days),
    () => collectKawasakiEvents(days),
    () => collectYokohamaEvents(days),
    () => collectSagamiharaEvents(days),
    () => collectEbinaEvents(days),
    () => collectKamakuraEvents(days),
    () => collectKamakuraKmspotEvents(days),
    () => collectYokosukaEvents(days),
    () => collectChigasakiEvents(days),
    () => collectZamaEvents(days),
    () => collectZushiEvents(days),
    () => collectYamatoEvents(days),
    () => collectHiratsukaEvents(days),
    () => collectHiratsukaLibraryEvents(days),
    () => collectOdawaraEvents(days),
    () => collectHadanoEvents(days),
    () => collectAyaseEvents(days),
    () => collectAtsugiEvents(days),
    () => collectAtsugiKosodateEvents(days),
    () => collectIseharaEvents(days),
    () => collectMinamiashigaraEvents(days),
    () => collectFujisawaEvents(days),
    () => collectSamukawaEvents(days),
    () => collectAikawaEvents(days),
    () => collectMiuraEvents(days),
    () => collectOisoEvents(days),
    () => collectHayamaEvents(days),
    () => collectNakaiEvents(days),
    () => collectKiyokawaEvents(days),
    () => collectNinomiyaEvents(days),
    () => collectOiEvents(days),
    () => collectYugawaraEvents(days),
    () => collectMatsudaEvents(days),
    () => collectManazuruEvents(days),
    () => collectHakoneEvents(days),
    () => collectKaiseiEvents(days),
    () => collectYamakitaEvents(days),
    () => collectMachidaKosodateEvents(days),
    () => collectMizuhoEvents(days),
    () => collectOkutamaEvents(days),
    () => collectHinodeEvents(days),
    () => collectHinoharaEvents(days),
    () => collectNagareyamaEvents(days),
    () => collectUrayasuEvents(days),
    () => collectNodaEvents(days),
    () => collectNarashinoEvents(days),
    () => collectShiroiEvents(days),
    () => collectKisarazuEvents(days),
    () => collectIsumiEvents(days),
    () => collectTohnoshoEvents(days),
    () => collectOtakiEvents(days),
    () => collectFunabashiEvents(days),
    () => collectNaritaEvents(days),
    () => collectChibaCityEvents(days),
    () => collectChibaCityWardEvents(days),
    () => collectKashiwaEvents(days),
    () => collectYachiyoEvents(days),
    () => collectAsahiEvents(days),
    () => collectKamogawaEvents(days),
    () => collectYokoshibahikariEvents(days),
    () => collectIchikawaEvents(days),
    () => collectIchikawaIkujiEvents(days),
    () => collectKatsuuraEvents(days),
    () => collectKimitsuEvents(days),
    () => collectKyonanEvents(days),
    () => collectYotsukaidoEvents(days),
    () => collectMatsudoEvents(days),
    () => collectAbikoEvents(days),
    () => collectKamagayaEvents(days),
    () => collectTomisatoEvents(days),
    () => collectShirakoEvents(days),
    () => collectKujukuriEvents(days),
    () => collectYachimataEvents(days),
    () => collectSodegauraEvents(days),
    () => collectIchinomiyaEvents(days),
    () => collectChoshiEvents(days),
    () => collectSakuraEvents(days),
    () => collectFuttsuEvents(days),
    () => collectInzaiEvents(days),
    () => collectKatoriEvents(days),
    () => collectToganeEvents(days),
    () => collectIchiharaEvents(days),
    () => collectSosaEvents(days),
    () => collectSammuEvents(days),
    () => collectSakaeChibaEvents(days),
    () => collectMobaraEvents(days),
    () => collectTateyamaEvents(days),
    () => collectMinamibosoEvents(days),
    () => collectOamishirasatoEvents(days),
    () => collectShisuiEvents(days),
    () => collectKozakiEvents(days),
    () => collectTakoEvents(days),
    () => collectShibayamaEvents(days),
    () => collectMutsuzawaEvents(days),
    () => collectChoseiEvents(days),
    () => collectNagaraEvents(days),
    () => collectOnjukuEvents(days),
    () => collectChonanEvents(days),
    () => collectKimitsuKosodateEvents(days),
    () => collectMatsudoKosodateEvents(days),
    () => collectMatsudoLibraryEvents(days),
    () => collectIchiharaKodomomiraiEvents(days),
    () => collectIchiharaSalonEvents(days),
    () => collectNaritaKosodateEvents(days),
    () => collectAbikoKosodateEvents(days),
    () => collectKamagayaKosodateEvents(days),
    () => collectSakuraLibraryEvents(days),
    () => collectInzaiLibraryEvents(days),
    () => collectKawaguchiEvents(days),
    () => collectKasukabeEvents(days),
    () => collectFujiminoEvents(days),
    () => collectMisatoEvents(days),
    () => collectKawagoeEvents(days),
    () => collectWakoEvents(days),
    () => collectWarabiEvents(days),
    () => collectAgeoEvents(days),
    () => collectNiizaEvents(days),
    () => collectAsakaEvents(days),
    () => collectTodaEvents(days),
    () => collectShikiEvents(days),
    () => collectFujimiEvents(days),
    () => collectSayamaEvents(days),
    () => collectYashioEvents(days),
    () => collectSaitamaEvents(days),
    () => collectSaitamaJidoukanEvents(days),
    () => collectSaitamaHokenEvents(days),
    () => collectKoshigayaEvents(days),
    () => collectKoshigayaKosodateEvents(days),
    () => collectTokorozawaEvents(days),
    () => collectKukiEvents(days),
    () => collectKumagayaEvents(days),
    () => collectKounosuEvents(days),
    () => collectSakadoEvents(days),
    () => collectHannoEvents(days),
    () => collectHigashimatsuyamaEvents(days),
    () => collectGyodaEvents(days),
    () => collectHonjoEvents(days),
    () => collectHidakaEvents(days),
    () => collectShiraokaEvents(days),
    () => collectSatteEvents(days),
    () => collectYoriiEvents(days),
    () => collectSugitoEvents(days),
    () => collectSokaEvents(days),
    () => collectTsurugashimaEvents(days),
    () => collectHasudaEvents(days),
    () => collectIrumaEvents(days),
    () => collectKazoEvents(days),
    () => collectFukayaEvents(days),
    () => collectOkegawaEvents(days),
    () => collectOgoseEvents(days),
    () => collectOgawaEvents(days),
    () => collectYoshimiEvents(days),
    () => collectKamikawaEvents(days),
    () => collectKamisatoEvents(days),
    () => collectYoshikawaEvents(days),
    () => collectOganoEvents(days),
    () => collectHigashichichibEvents(days),
    () => collectKawajimaEvents(days),
    () => collectKitamotoEvents(days),
    () => collectInaEvents(days),
    () => collectYokozeEvents(days),
    () => collectNagatoroEvents(days),
    () => collectMiyoshiEvents(days),
    () => collectHatoyamaEvents(days),
    () => collectMiyashiroEvents(days),
    () => collectChichibuEvents(days),
    () => collectNamegawaEvents(days),
    () => collectRanzanEvents(days),
    () => collectMatsubushiEvents(days),
    () => collectMinanoEvents(days),
    () => collectMoroyamaEvents(days),
    () => collectHanyuEvents(days),
    () => collectMisatoSaitamaEvents(days),
    // Tochigi
    () => collectSanoEvents(days),
    () => collectNikkoEvents(days),
    () => collectMokaEvents(days),
    () => collectNasushiobaraEvents(days),
    () => collectTochigiCityEvents(days),
    () => collectYaitaEvents(days),
    () => collectUtsunomiyaEvents(days),
    () => collectAshikagaEvents(days),
    () => collectKanumaEvents(days),
    () => collectOyamaEvents(days),
    () => collectOhtawaraEvents(days),
    () => collectTochigiSakuraEvents(days),
    () => collectNasukarasuyamaEvents(days),
    () => collectShimotsukeEvents(days),
    () => collectKaminokawaEvents(days),
    () => collectMashikoEvents(days),
    () => collectMotegiEvents(days),
    () => collectIchikaiEvents(days),
    () => collectHagaEvents(days),
    () => collectMibuEvents(days),
    () => collectNogiEvents(days),
    () => collectShioyaEvents(days),
    () => collectTakanezawaEvents(days),
    () => collectNasuEvents(days),
    () => collectTochigiNakagawaEvents(days),
    // Gunma
    () => collectMaebashiEvents(days),
    () => collectIsesakiEvents(days),
    () => collectFujiokaGunmaEvents(days),
    () => collectTakasakiEvents(days),
    () => collectOtaGunmaEvents(days),
    () => collectAnnakaEvents(days),
    () => collectNakanojoEvents(days),
    () => collectKiryuEvents(days),
    () => collectNumataEvents(days),
    () => collectTatebayashiEvents(days),
    () => collectShibukawaEvents(days),
    () => collectTomiokaEvents(days),
    () => collectMidoriEvents(days),
    () => collectShintoEvents(days),
    () => collectYoshiokaEvents(days),
    () => collectUenoGunmaEvents(days),
    () => collectKannaEvents(days),
    () => collectShimonitaEvents(days),
    () => collectNanmokuEvents(days),
    () => collectKanraEvents(days),
    () => collectNaganoharaEvents(days),
    () => collectTsumagoiEvents(days),
    () => collectKusatsuEvents(days),
    () => collectTakayamaGunmaEvents(days),
    () => collectHigashiagatsumaEvents(days),
    () => collectKatashinaEvents(days),
    () => collectKawabaEvents(days),
    () => collectShowaGunmaEvents(days),
    () => collectMinakamiEvents(days),
    () => collectTamamuraEvents(days),
    () => collectItakuraEvents(days),
    () => collectMeiwaGunmaEvents(days),
    () => collectChiyodaGunmaEvents(days),
    () => collectOizumiEvents(days),
    () => collectOraEvents(days),
    // Tochigi schedule supplement
    () => collectNasuScheduleEvents(days),
    () => collectTakanezawaScheduleEvents(days),
    () => collectNikkoScheduleEvents(days),
    () => collectNikkoSupportCenterEvents(days),
    () => collectNasushiobaraScheduleEvents(days),
    () => collectOyamaScheduleEvents(days),
    () => collectOhtawaraScheduleEvents(days),
    () => collectAshikagaScheduleEvents(days),
    () => collectShimotsukeScheduleEvents(days),
    () => collectTochigiSakuraScheduleEvents(days),
    () => collectOhtawaraPdfScheduleEvents(days),
    () => collectKanumaPdfScheduleEvents(days),
    () => collectNasukarasuyamaPdfScheduleEvents(days),
    // PDF schedule collectors
    () => collectOtaGunmaPdfScheduleEvents(days),
    () => collectShibukawaPdfScheduleEvents(days),
    () => collectTomiokaPdfScheduleEvents(days),
    () => collectAnnakaPdfScheduleEvents(days),
    () => collectMinakamiPdfScheduleEvents(days),
    () => collectMeiwaPdfScheduleEvents(days),
    () => collectShintoPdfScheduleEvents(days),
    // Gunma schedule supplements
    () => collectMaebashiScheduleEvents(days),
    () => collectIsesakiScheduleEvents(days),
    () => collectKiryuScheduleEvents(days),
    () => collectTatebayashiScheduleEvents(days),
    () => collectNumataScheduleEvents(days),
    () => collectKawabaScheduleEvents(days),
    () => collectShimonitaScheduleEvents(days),
    () => collectChiyodaGunmaScheduleEvents(days),
    () => collectFujiokaGunmaScheduleEvents(days),
    () => collectTamamuraScheduleEvents(days),
    () => collectKanraScheduleEvents(days),
    () => collectAnnakaScheduleEvents(days),
    () => collectHigashiagatsumaScheduleEvents(days),
    () => collectItakuraCalendarEvents(days),
    () => collectMidoriScheduleEvents(days),
    () => collectOizumiScheduleEvents(days),
    () => collectOtaKodomokanEvents(days),
    () => collectKiryuShienCenterEvents(days),
    () => collectNakanojoRecurringEvents(days),
    () => collectShimonitaCrossRowEvents(days),
    () => collectTakasakiNandemoEvents(days),
    // Katsushika schedule supplement
    () => collectKatsushikaScheduleEvents(days),
    // Ibaraki
    () => collectHitachiIbEvents(days),
    () => collectHitachinakaEvents(days),
    () => collectMoriyaEvents(days),
    () => collectKamisuEvents(days),
    () => collectTokaiIbEvents(days),
    () => collectKogaIbEvents(days),
    () => collectTsukubaEvents(days),
    () => collectRyugasakiEvents(days),
    () => collectTorideEvents(days),
    () => collectMitoEvents(days),
    () => collectKashimaIbEvents(days),
    () => collectKasamaEvents(days),
    () => collectChikuseiEvents(days),
    () => collectTsuchiuraEvents(days),
    () => collectIshiokaEvents(days),
    () => collectJosoEvents(days),
    () => collectNakaIbEvents(days),
    () => collectBandoEvents(days),
    () => collectHitachiotaEvents(days),
    () => collectYukiEvents(days),
    () => collectTsukubamiraiEvents(days),
    () => collectInashikiEvents(days),
    () => collectSakuragawaEvents(days),
    () => collectHitachiomiyaEvents(days),
    () => collectShimotsumaEvents(days),
    () => collectHokotaEvents(days),
    () => collectNamegataEvents(days),
    () => collectItakoEvents(days),
    () => collectKasumigauraEvents(days),
    () => collectTakahagiEvents(days),
    () => collectShiroIbEvents(days),
    () => collectSakaiIbEvents(days),
    () => collectDaigoEvents(days),
    // Ibaraki extra 9
    () => collectYachiyoIbEvents(days),
    () => collectGokaEvents(days),
    () => collectOaraiEvents(days),
    () => collectKawachiIbEvents(days),
    () => collectIbarakimachiEvents(days),
    () => collectKitaibarakiEvents(days),
    () => collectUshikuEvents(days),
    () => collectAmiEvents(days),
    () => collectToneIbEvents(days),
    // 東北6県
    () => collectHachinoheEvents(days),
    () => collectTsugaruEvents(days),
    () => collectHiranaiEvents(days),
    () => collectNakadomariEvents(days),
    () => collectYomogitaEvents(days),
    () => collectItayanagiEvents(days),
    () => collectKitakamiEvents(days),
    () => collectKujiEvents(days),
    () => collectOshuEvents(days),
    () => collectNishiwagaEvents(days),
    () => collectIchinoheEvents(days),
    () => collectOtsuchiEvents(days),
    () => collectMiyagiSendaiEvents(days),
    () => collectIshinomakiEvents(days),
    () => collectHigashimatsushimaEvents(days),
    () => collectZaoEvents(days),
    () => collectShichikashukuEvents(days),
    () => collectShichigahamaEvents(days),
    () => collectTaiwaEvents(days),
    () => collectShikamaEvents(days),
    () => collectNatoriEvents(days),
    () => collectShiogamaEvents(days),
    () => collectAkitaKosodateEvents(days),
    () => collectYokoteEvents(days),
    () => collectYurihonjyoEvents(days),
    () => collectOgaEvents(days),
    () => collectKosakaEvents(days),
    () => collectHachirogataEvents(days),
    () => collectYonezawaEvents(days),
    () => collectSakataEvents(days),
    () => collectShinjoEvents(days),
    () => collectNagaiEvents(days),
    () => collectNakayamaYmEvents(days),
    () => collectKahokuEvents(days),
    () => collectAsahiYmEvents(days),
    () => collectKaneyamaYmEvents(days),
    () => collectMamurogawaEvents(days),
    () => collectOkuraEvents(days),
    () => collectShiratakaEvents(days),
    () => collectFukushimaCityEvents(days),
    () => collectSomaEvents(days),
    () => collectMinamisomaEvents(days),
    () => collectOtamaEvents(days),
    () => collectShimogoEvents(days),
    () => collectAizumisatoEvents(days),
    () => collectFurudonoEvents(days),
    // 北海道
    () => collectHokkaidoIwamizawaEvents(days),
    () => collectHokkaidoShibetsuEvents(days),
    () => collectHokkaidoChitoseEvents(days),
    () => collectHokkaidoMoriEvents(days),
    () => collectHokkaidoOzoraEvents(days),
    () => collectHokkaidoTsubetsuEvents(days),
    () => collectHokkaidoTaikiEvents(days),
    () => collectHokkaidoNisekoEvents(days),
    () => collectHokkaidoShiraoiEvents(days),
    () => collectHokkaidoHigashikaguraEvents(days),
    () => collectHokkaidoOtoineppuEvents(days),
    () => collectHokkaidoYubetsuEvents(days),
    () => collectHokkaidoNakasatsunaiEvents(days),
    () => collectHokkaidoSarabetsuEvents(days),
    () => collectHokkaidoHonbetsuEvents(days),
    () => collectHokkaidoHirooEvents(days),
    () => collectHokkaidoShikaoiEvents(days),
    () => collectHokkaidoAkkeshiEvents(days),
    () => collectHokkaidoBetsukaiEvents(days),
    () => collectHokkaidoNakashibetsuEvents(days),
    () => collectHokkaidoShibetsuChoEvents(days),
    () => collectHokkaidoShintokuEvents(days),
    () => collectHokkaidoKutchanEvents(days),
    () => collectHokkaidoHaboroEvents(days),
    // 中部
    () => collectNiigataSanjoEvents(days),
    () => collectNiigataKashiwazakiEvents(days),
    () => collectNiigataTsubameEvents(days),
    () => collectNiigataAganoEvents(days),
    () => collectNiigataSeiroEvents(days),
    () => collectNiigataYuzawaEvents(days),
    () => collectNiigataKamoEvents(days),
    () => collectNiigataMinamiuonumaEvents(days),
    () => collectNiigataTagamiEvents(days),
    () => collectToyamaHimiEvents(days),
    () => collectToyamaNamerikawaEvents(days),
    () => collectToyamaKurobeEvents(days),
    () => collectToyamaNyuzenEvents(days),
    () => collectToyamaAsahiTyEvents(days),
    () => collectIshikawaKanazawaEvents(days),
    () => collectIshikawaKomatsuEvents(days),
    () => collectIshikawaKagaEvents(days),
    () => collectIshikawaNakanotoEvents(days),
    () => collectFukuiFukuikuEvents(days),
    () => collectFukuiSabaeEvents(days),
    () => collectYamanashiChuoEvents(days),
    () => collectYamanashiMinamialpsEvents(days),
    () => collectYamanashiHokutoEvents(days),
    () => collectNaganoSuzakaEvents(days),
    () => collectNaganoKomaganeEvents(days),
    () => collectNaganoChikumaEvents(days),
    () => collectNaganoIijimachoEvents(days),
    () => collectNaganoMatsukawaEvents(days),
    () => collectNaganoIkedaEvents(days),
    () => collectGifuOgakiEvents(days),
    () => collectGifuSekiEvents(days),
    () => collectGifuEnaEvents(days),
    () => collectGifuMotosuEvents(days),
    () => collectGifuKaizuEvents(days),
    () => collectGifuAnpachiEvents(days),
    () => collectGifuIbigawaEvents(days),
    () => collectGifuOnoGfEvents(days),
    () => collectShizuokaFujiedaEvents(days),
    () => collectShizuokaSusonoEvents(days),
    () => collectShizuokaKosaiEvents(days),
    () => collectShizuokaIzuEvents(days),
    () => collectShizuokaOmaezakiEvents(days),
    () => collectShizuokaNagaizumiEvents(days),
    () => collectShizuokaKannamiEvents(days),
    () => collectShizuokaHamamatsuEvents(days),
    () => collectShizuokaCityEvents(days),
    () => collectAichiToyokawaEvents(days),
    () => collectAichiHekinanEvents(days),
    () => collectAichiShinshiroEvents(days),
    () => collectAichiChiryuEvents(days),
    () => collectAichiInazawaEvents(days),
    () => collectAichiIwakuraEvents(days),
    () => collectAichiNisshinEvents(days),
    () => collectAichiAisaiEvents(days),
    () => collectAichiMiyoshiEvents(days),
    () => collectAichiNagakuteEvents(days),
    () => collectAichiTogoEvents(days),
    () => collectAichiAguiEvents(days),
    () => collectAichiHigashiuraEvents(days),
    () => collectAichiOwariasahiEvents(days),
    () => collectAichiKomakiEvents(days),
    () => collectAichiNagoyaEvents(days),
    () => collectAichiToyotaEvents(days),
    () => collectAichiKasugaiEvents(days),
    () => collectAichiIchinomiyaEvents(days),
    () => collectGifuGifuEvents(days),
    // 近畿
    () => collectShigaOtsuEvents(days),
    () => collectShigaMoriyamaEvents(days),
    () => collectMieTsuEvents(days),
    () => collectMieTobaEvents(days),
    () => collectMieOwaseEvents(days),
    () => collectMieIgaEvents(days),
    () => collectMieKisosakiEvents(days),
    () => collectMieTakiEvents(days),
    () => collectMieMeiwaEvents(days),
    () => collectShigaHikoneEvents(days),
    () => collectShigaNagahamaEvents(days),
    () => collectShigaOmihachimanEvents(days),
    () => collectShigaKokaEvents(days),
    () => collectShigaMaibaraEvents(days),
    () => collectShigaAishoEvents(days),
    () => collectShigaHinoEvents(days),
    () => collectShigaToyosatoEvents(days),
    () => collectKyotoMaizuruEvents(days),
    () => collectKyotoAyabeEvents(days),
    () => collectKyotoJoyoEvents(days),
    () => collectKyotoNagaokakyoEvents(days),
    () => collectKyotoYawataEvents(days),
    () => collectKyotoSeikaEvents(days),
    () => collectKyotoKumiyamaEvents(days),
    () => collectKyotoMinamiyamashiroEvents(days),
    () => collectKyotoKameokaEvents(days),
    () => collectKyotoUjiEvents(days),
    () => collectKyotoMukoEvents(days),
    () => collectKyotoMamafreEvents(days),
    () => collectKyotoWakutobiEvents(days),
    () => collectOsakaIkedaEvents(days),
    () => collectOsakaIzumiotsuEvents(days),
    () => collectOsakaKaizukaEvents(days),
    () => collectOsakaMoriguchiEvents(days),
    () => collectOsakaIbarakiEvents(days),
    () => collectOsakaHirakataEvents(days),
    () => collectOsakaNeyagawaEvents(days),
    () => collectOsakaIzumiEvents(days),
    () => collectOsakaHabikinoEvents(days),
    () => collectOsakaFujiideraEvents(days),
    () => collectOsakaHigashiosakaEvents(days),
    () => collectOsakaSennanEvents(days),
    () => collectOsakaHannanEvents(days),
    () => collectOsakaKumatoriEvents(days),
    () => collectOsakaTadaokaEvents(days),
    () => collectOsakaTaishiEvents(days),
    () => collectOsakaTakatsukiEvents(days),
    () => collectOsakaKishiwadaEvents(days),
    () => collectOsakaKawachinaganoEvents(days),
    () => collectOsakaTondabayashiEvents(days),
    () => collectOsakaSakaiEvents(days),
    () => collectOsakaSuitaEvents(days),
    () => collectHyogoAshiyaEvents(days),
    () => collectHyogoHimejiEvents(days),
    () => collectHyogoItamiEvents(days),
    () => collectHyogoKakogawaEvents(days),
    () => collectHyogoTatsunoEvents(days),
    () => collectHyogoOnoEvents(days),
    () => collectHyogoShisoEvents(days),
    () => collectHyogoKatoEvents(days),
    () => collectHyogoInagawaEvents(days),
    () => collectHyogoInamiEvents(days),
    () => collectHyogoFukusakiEvents(days),
    () => collectHyogoKamikawaEvents(days),
    () => collectNaraTenriEvents(days),
    () => collectNaraKashiharaEvents(days),
    () => collectNaraGojoEvents(days),
    () => collectNaraGoseEvents(days),
    () => collectNaraIkomaEvents(days),
    () => collectNaraIkarugaEvents(days),
    () => collectNaraAndoEvents(days),
    () => collectNaraKawanishiNrEvents(days),
    () => collectNaraTawaramotoEvents(days),
    () => collectNaraOjiEvents(days),
    () => collectNaraKoryoEvents(days),
    () => collectNaraAsukaEvents(days),
    () => collectNaraTotsukawaEvents(days),
    () => collectNaraShimoichiEvents(days),
    () => collectWakayamaHashimotoEvents(days),
    () => collectWakayamaInamiWkEvents(days),
    // 中国・四国
    () => collectTottoriKosodateEvents(days),
    () => collectTottoriNichinanEvents(days),
    () => collectTottoriSakaiminatoEvents(days),
    () => collectShimaneMasudaEvents(days),
    () => collectShimaneAmaEvents(days),
    () => collectOkayamaOkayamaEvents(days),
    () => collectOkayamaAkaiwaEvents(days),
    () => collectOkayamaMimasakaEvents(days),
    () => collectOkayamaHayashimaEvents(days),
    () => collectHiroshimaFuchuEvents(days),
    () => collectHiroshimaOtakeEvents(days),
    () => collectHiroshimaHigashihiroshimaEvents(days),
    () => collectHiroshimaIkuchanEvents(days),
    () => collectHiroshimaFukuyamaEvents(days),
    () => collectHiroshimaKureEvents(days),
    () => collectHiroshimaOnomichiEvents(days),
    () => collectHiroshimaMiharaEvents(days),
    () => collectHiroshimaHatsukaichiEvents(days),
    () => collectYamaguchiHikariEvents(days),
    () => collectYamaguchiShimonosekiEvents(days),
    () => collectYamaguchiYamaguchiEvents(days),
    () => collectYamaguchiShunanEvents(days),
    () => collectTokushimaTokushimaEvents(days),
    () => collectTokushimaNakaEvents(days),
    () => collectTokushimaHigashimiyoshiEvents(days),
    () => collectKagawaTakamatsuEvents(days),
    () => collectKagawaSanukiEvents(days),
    () => collectKagawaMitoyoEvents(days),
    () => collectKagawaTonoshoEvents(days),
    () => collectEhimeSeiyoEvents(days),
    () => collectEhimeTobeEvents(days),
    () => collectKochiMurotoEvents(days),
    () => collectKochiKokohareEvents(days),
    // 九州・沖縄
    () => collectFukuokaKitakyushuEvents(days),
    () => collectFukuokaFukutsuEvents(days),
    () => collectFukuokaShinguFkEvents(days),
    () => collectFukuokaHirokawaEvents(days),
    () => collectFukuokaKawaraEvents(days),
    () => collectFukuokaChikushinoEvents(days),
    () => collectFukuokaNakagawaEvents(days),
    () => collectNagasakiTsushimaEvents(days),
    () => collectNagasakiIkiEvents(days),
    () => collectNagasakiSaikaiEvents(days),
    () => collectNagasakiTogitsuEvents(days),
    () => collectNagasakiHigashisonogiEvents(days),
    () => collectSagaKaratsuEvents(days),
    () => collectSagaTosuEvents(days),
    () => collectKumamotoTakamoriEvents(days),
    () => collectKumamotoKikuchiEvents(days),
    () => collectOitaHitaEvents(days),
    () => collectOitaTaketaEvents(days),
    () => collectOitaKitsukiEvents(days),
    () => collectOitaKusuEvents(days),
    () => collectMiyazakiMiyazakiEvents(days),
    () => collectMiyazakiNichinanEvents(days),
    () => collectMiyazakiKijoEvents(days),
    () => collectMiyazakiKadogawaEvents(days),
    () => collectMiyazakiMiyakojoEvents(days),
    () => collectKagoshimaSatsumasendaiEvents(days),
    () => collectKagoshimaMinamikyushuEvents(days),
    () => collectKagoshimaSatsumaEvents(days),
    () => collectKagoshimaKimotsukiEvents(days),
    () => collectOkinawaYomitanEvents(days),
    () => collectOkinawaKitanakagusukuEvents(days),
    () => collectOkinawaIeEvents(days),
    () => collectHokkaidoSapporoEvents(days),
    () => collectOitaOitaEvents(days),
    () => collectOkinawaNahaEvents(days),
    () => collectShizuokaAtamiEvents(days),
    () => collectShizuokaItoEvents(days),
    () => collectAichiKiyosuEvents(days),
    () => collectOkayamaKibichuoEvents(days),
  ], 5);
  // Flatten all collector results into a single array.
  // Most collectors return an array; additional-wards returns an object of arrays.
  const rawItems = [];
  for (const result of allCollectorResults) {
    if (Array.isArray(result)) {
      rawItems.push(...result);
    } else if (result && typeof result === "object") {
      for (const arr of Object.values(result)) {
        if (Array.isArray(arr)) rawItems.push(...arr);
      }
    }
  }
  const items = rawItems
    .map((ev) => {
      const { point, query_hit, recently_updated, ...rest } = ev;
      if (typeof rest.time_unknown === "boolean") return rest;
      let inferredUnknown = false;
      if (!rest.ends_at && rest.starts_at) {
        const d = new Date(rest.starts_at);
        if (!Number.isNaN(d.getTime())) {
          const hm = new Intl.DateTimeFormat("ja-JP", {
            timeZone: "Asia/Tokyo",
            hour: "2-digit",
            minute: "2-digit",
            hour12: false,
          }).format(d);
          inferredUnknown = hm === "00:00";
        }
      }
      return { ...rest, time_unknown: inferredUnknown };
    })
    .sort((a, b) => a.starts_at.localeCompare(b.starts_at));
  const now = parseYmdFromJst(new Date());
  const end = new Date();
  end.setUTCDate(end.getUTCDate() + days);
  const endJst = parseYmdFromJst(end);

  const payload = {
    date_jst: `${now.key}..${endJst.key}`,
    count: items.length,
    source: "tokyo_jidokan",
    debug_counts: {
      raw: (() => {
        const counts = {};
        for (const ev of rawItems) {
          const key = ev.source || "unknown";
          counts[key] = (counts[key] || 0) + 1;
        }
        return counts;
      })(),
    },
    items,
    refresh_in_progress: false,
  };

  cache.key = cacheKey;
  cache.data = payload;
  cache.savedAt = Date.now();

  if (snapshotPath) saveSnapshot(snapshotPath, payload);
  if (geoCachePath && geoCache) saveGeoCache(geoCachePath, geoCache);

  return {
    ...payload,
    from_cache: false,
    snapshot_saved_at: new Date(cache.savedAt).toISOString(),
  };
};
}

module.exports = {
  createGetEvents,
};
